# Generated by Django 5.1 on 2026-05-25 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('konten', '0007_remove_konto_objekt'),
        ('objekte', '0021_alter_objekt_auto_pipeline_aktiv_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wirtschaftsplan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('beschlossen', 'Beschlossen'), ('aktiv', 'Aktiv'), ('aufgehoben', 'Aufgehoben')], default='entwurf', max_length=12)),
                ('gesamtsumme', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gesamtsumme_hausgeld', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gesamtsumme_ruecklage', models.JSONField(default=dict)),
                ('beschluss_datum', models.DateField(blank=True, null=True)),
                ('beschluss_tagesordnungspunkt', models.CharField(blank=True, max_length=100, null=True)),
                ('wirkung_ab', models.DateField()),
                ('bemerkung', models.TextField(blank=True, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('beschlossen_am', models.DateTimeField(blank=True, null=True)),
                ('aufhebt_wp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abgeloest_durch', to='abrechnung_wp.wirtschaftsplan')),
                ('beschlossen_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beschlossene_wirtschaftsplaene', to=settings.AUTH_USER_MODEL)),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_wirtschaftsplaene', to=settings.AUTH_USER_MODEL)),
                ('wirtschaftsjahr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wirtschaftsplaene', to='objekte.wirtschaftsjahr')),
            ],
            options={
                'verbose_name': 'Wirtschaftsplan',
                'verbose_name_plural': 'Wirtschaftspläne',
                'ordering': ['-wirtschaftsjahr__jahr', 'status'],
            },
        ),
        migrations.CreateModel(
            name='WirtschaftsplanPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vs_code', models.CharField(max_length=3)),
                ('betrag', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('verteilung_validiert', models.BooleanField(default=False)),
                ('verteilung_freigegeben_trotz_diff', models.BooleanField(default=False)),
                ('bemerkung', models.CharField(blank=True, max_length=255, null=True)),
                ('konto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wp_positionen', to='konten.konto')),
                ('wirtschaftsplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='abrechnung_wp.wirtschaftsplan')),
            ],
            options={
                'verbose_name': 'Wirtschaftsplan-Position',
                'verbose_name_plural': 'Wirtschaftsplan-Positionen',
                'ordering': ['konto__kontonummer'],
            },
        ),
        migrations.CreateModel(
            name='WirtschaftsplanAnteil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vs_anteil_einheit', models.DecimalField(decimal_places=6, max_digits=18)),
                ('vs_anteil_gesamt', models.DecimalField(decimal_places=6, max_digits=18)),
                ('betrag_anteil', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monatsbetrag_anteil', models.DecimalField(decimal_places=2, max_digits=12)),
                ('einheit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wp_anteile', to='objekte.einheit')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anteile', to='abrechnung_wp.wirtschaftsplanposition')),
            ],
            options={
                'verbose_name': 'Wirtschaftsplan-Anteil',
                'verbose_name_plural': 'Wirtschaftsplan-Anteile',
                'ordering': ['einheit__einheit_nr'],
            },
        ),
        migrations.AddConstraint(
            model_name='wirtschaftsplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['beschlossen', 'aktiv'])), fields=('wirtschaftsjahr', 'status'), name='uniq_wp_wj_aktiv_beschlossen'),
        ),
        migrations.AddConstraint(
            model_name='wirtschaftsplanposition',
            constraint=models.UniqueConstraint(fields=('wirtschaftsplan', 'konto'), name='uniq_wp_position_wp_konto'),
        ),
        migrations.AddConstraint(
            model_name='wirtschaftsplanposition',
            constraint=models.CheckConstraint(condition=models.Q(('betrag__gte', 0)), name='wp_position_betrag_nicht_negativ'),
        ),
        migrations.AddConstraint(
            model_name='wirtschaftsplananteil',
            constraint=models.UniqueConstraint(fields=('position', 'einheit'), name='uniq_wp_anteil_position_einheit'),
        ),
    ]
