# Generated by Django 5.2.12 on 2026-04-03 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objekte', '0001_initial'),
        ('personen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nummer', models.CharField(max_length=10)),
                ('bezeichnung', models.CharField(max_length=255)),
                ('klasse', models.IntegerField()),
                ('verteilerschluessel', models.CharField(choices=[('MEA', 'Miteigentumsanteil'), ('Flaeche', 'Fläche'), ('Kopf', 'Kopf')], max_length=10)),
                ('aktiv', models.BooleanField(default=True)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konten', to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Konto (Sachkonto)',
                'verbose_name_plural': 'Konten (Sachkonten)',
                'ordering': ['objekt', 'nummer'],
                'unique_together': {('objekt', 'nummer')},
            },
        ),
        migrations.CreateModel(
            name='Personenkonto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kontonummer', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('archiviert', 'Archiviert')], default='aktiv', max_length=20)),
                ('archiviert_am', models.DateField(blank=True, null=True)),
                ('eigentuemer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personenkonten', to='personen.person')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personenkonten', to='objekte.objekt')),
                ('vertrag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personenkonto', to='personen.eigentumsverhaeltnis')),
            ],
            options={
                'verbose_name': 'Personenkonto',
                'verbose_name_plural': 'Personenkonten',
                'ordering': ['objekt', 'kontonummer'],
                'unique_together': {('objekt', 'kontonummer')},
            },
        ),
        migrations.CreateModel(
            name='Unterkonto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suffix', models.CharField(max_length=4)),
                ('bezeichnung', models.CharField(max_length=255)),
                ('bankkonto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unterkonten', to='objekte.bankkonto')),
                ('personenkonto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unterkonten', to='konten.personenkonto')),
                ('sachkonto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unterkonten', to='konten.konto')),
            ],
            options={
                'verbose_name': 'Unterkonto',
                'verbose_name_plural': 'Unterkonten',
                'ordering': ['personenkonto', 'suffix'],
                'unique_together': {('personenkonto', 'suffix')},
            },
        ),
    ]
