# Generated by Django 5.2.12 on 2026-04-19 17:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0002_konto_update'),
        ('objekte', '0011_remove_vs101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abrechnungsart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3)),
                ('bezeichnung', models.CharField(max_length=100)),
                ('aktiv', models.BooleanField(default=True)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abrechnungsarten', to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Abrechnungsart',
                'verbose_name_plural': 'Abrechnungsarten',
                'ordering': ['code'],
                'unique_together': {('objekt', 'code')},
            },
        ),
    ]
