# Generated by Django 5.1 on 2026-05-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0004_konto_objekt_nullable'),
        ('konten', '0005_data_migration_wj'),
    ]

    operations = [
    ]
