# Generated by Django 5.1 on 2026-05-24 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0006_merge_20260525_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konto',
            name='objekt',
        ),
    ]
