# Generated by Django 5.1 on 2026-07-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0007_remove_konto_objekt'),
    ]

    operations = [
        migrations.AddField(
            model_name='konto',
            name='umlagefaehig',
            field=models.BooleanField(default=True, help_text='Kosten dieses Kontos sind umlagefähig — steuert die Gliederung der Jahresabrechnung (umlagefähig / nicht umlagefähig).'),
        ),
    ]
