# Generated by Django 5.1 on 2026-08-17 15:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objekte', '0021_alter_objekt_auto_pipeline_aktiv_and_more'),
        ('rechnungen', '0023_rechnung_status_wkz_beleg'),
        ('vorgaenge', '0004_seed_antwort_vorschlag_aktiv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandwerkerauftragNummerZaehler',
            fields=[
                ('jahr', models.IntegerField(primary_key=True, serialize=False)),
                ('letzter_zaehler', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Handwerkerauftrag-Nummer-Zähler',
                'verbose_name_plural': 'Handwerkerauftrag-Nummer-Zähler',
            },
        ),
        migrations.CreateModel(
            name='Gewerk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('bezeichnung', models.CharField(max_length=100)),
                ('aktiv', models.BooleanField(default=True)),
                ('sortierung', models.IntegerField(default=0)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_gewerke', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gewerk',
                'verbose_name_plural': 'Gewerke',
                'ordering': ['sortierung', 'bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='Handwerkerauftrag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nummer', models.CharField(editable=False, max_length=20, unique=True)),
                ('titel', models.CharField(max_length=255)),
                ('beschreibung', models.TextField(blank=True)),
                ('gewuenscht_ab', models.DateField(blank=True, null=True)),
                ('prioritaet', models.CharField(choices=[('niedrig', 'Niedrig'), ('normal', 'Normal'), ('hoch', 'Hoch')], default='normal', max_length=10)),
                ('geschaetzte_kosten', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('versendet', 'Versendet'), ('angenommen', 'Angenommen'), ('abgelehnt', 'Abgelehnt'), ('in_arbeit', 'In Arbeit'), ('abgeschlossen', 'Abgeschlossen'), ('storniert', 'Storniert'), ('abgelaufen', 'Abgelaufen')], default='entwurf', max_length=20)),
                ('versendet_am', models.DateTimeField(blank=True, null=True)),
                ('angenommen_am', models.DateTimeField(blank=True, null=True)),
                ('abgelehnt_am', models.DateTimeField(blank=True, null=True)),
                ('ablehnung_grund', models.TextField(blank=True)),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True)),
                ('abschluss_notiz', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_handwerkerauftraege', to=settings.AUTH_USER_MODEL)),
                ('kreditor', models.ForeignKey(limit_choices_to={'ist_handwerker': True}, on_delete=django.db.models.deletion.PROTECT, related_name='handwerkerauftraege', to='rechnungen.kreditor')),
                ('objekt', models.ForeignKey(help_text='Pflichtfeld — Adresse und Handwerkerzuordnung hängen daran.', on_delete=django.db.models.deletion.PROTECT, related_name='handwerkerauftraege', to='objekte.objekt')),
                ('vorgang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handwerkerauftraege', to='vorgaenge.vorgang')),
            ],
            options={
                'verbose_name': 'Handwerkerauftrag',
                'verbose_name_plural': 'Handwerkeraufträge',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='AuftragsbestaetigungsToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accept_token', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('reject_token', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('gueltig_bis', models.DateTimeField()),
                ('verbraucht_am', models.DateTimeField(blank=True, help_text='Einmalverwendung — gesetzt sobald Accept- oder Reject-Link benutzt wurde. Bewusst kein Boolean-Feld (würde eine zweite Wahrheit neben gueltig_bis erzeugen).', null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('auftrag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='handwerker.handwerkerauftrag')),
            ],
            options={
                'verbose_name': 'Auftragsbestätigungs-Token',
                'verbose_name_plural': 'Auftragsbestätigungs-Token',
            },
        ),
        migrations.CreateModel(
            name='HandwerkerauftragEreignis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[('statuswechsel', 'Statuswechsel'), ('versand', 'Versand'), ('versand_fehlgeschlagen', 'Versand fehlgeschlagen'), ('kommentar', 'Kommentar'), ('rechnung_zugeordnet', 'Rechnung zugeordnet'), ('system_abgelaufen', 'System: Auftrag abgelaufen')], max_length=30)),
                ('text', models.TextField(blank=True, null=True)),
                ('alter_wert', models.CharField(blank=True, max_length=100, null=True)),
                ('neuer_wert', models.CharField(blank=True, max_length=100, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('auftrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ereignisse', to='handwerker.handwerkerauftrag')),
                ('erstellt_von', models.ForeignKey(blank=True, help_text='None = System-Ereignis (z.B. automatischer Ablauf).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_handwerkerauftrag_ereignisse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Handwerkerauftrag-Ereignis',
                'verbose_name_plural': 'Handwerkerauftrag-Ereignisse',
                'ordering': ['erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='ObjektHandwerker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prioritaet', models.PositiveIntegerField(default=1)),
                ('notiz', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('kreditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objekt_zuordnungen', to='rechnungen.kreditor')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handwerker_zuordnungen', to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Objekt-Handwerker-Zuordnung',
                'verbose_name_plural': 'Objekt-Handwerker-Zuordnungen',
                'ordering': ['prioritaet', 'kreditor__name'],
            },
        ),
        migrations.AddIndex(
            model_name='handwerkerauftrag',
            index=models.Index(fields=['objekt', 'status'], name='handwerker__objekt__2aa4bd_idx'),
        ),
        migrations.AddIndex(
            model_name='handwerkerauftrag',
            index=models.Index(fields=['kreditor', 'status'], name='handwerker__kredito_4f700a_idx'),
        ),
        migrations.AddIndex(
            model_name='handwerkerauftrag',
            index=models.Index(fields=['erstellt_am'], name='handwerker__erstell_270392_idx'),
        ),
        migrations.AddConstraint(
            model_name='objekthandwerker',
            constraint=models.UniqueConstraint(fields=('objekt', 'kreditor'), name='unique_objekt_handwerker'),
        ),
    ]
