# Generated by Django 5.2.12 on 2026-04-03 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objekte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datei', models.FileField(upload_to='dokumente/')),
                ('dateiname', models.CharField(max_length=255)),
                ('kategorie', models.CharField(max_length=100)),
                ('beschreibung', models.TextField(blank=True)),
                ('verknuepfung_typ', models.CharField(max_length=50)),
                ('hochgeladen_am', models.DateTimeField(auto_now_add=True)),
                ('einheit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='objekte.einheit')),
                ('hochgeladen_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hochgeladene_dokumente', to=settings.AUTH_USER_MODEL)),
                ('objekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ['-hochgeladen_am'],
            },
        ),
    ]
