# Generated by Django 5.1 on 2026-05-26 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumente', '0001_initial'),
        ('objekte', '0021_alter_objekt_auto_pipeline_aktiv_and_more'),
        ('rechnungen', '0013_merge_0011_wkz_models_0012_rechnung_sepa_lastschrift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BelegnummerZaehler',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('letzter_zaehler', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Belegnummer-Zähler',
            },
        ),
        migrations.CreateModel(
            name='Beleg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('belegnummer', models.CharField(editable=False, help_text='Systemweit eindeutige, unveränderliche Belegnummer (AA00000001 …)', max_length=12, unique=True)),
                ('typ', models.CharField(choices=[('rechnung', 'Rechnung'), ('dokument', 'Dokument'), ('wiederkehrend', 'Wiederkehrende Zahlung'), ('sonstiges', 'Sonstiges')], max_length=20)),
                ('beschreibung', models.CharField(blank=True, max_length=500)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('dokument', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beleg', to='dokumente.dokument')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_belege', to=settings.AUTH_USER_MODEL)),
                ('objekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='belege', to='objekte.objekt')),
                ('rechnung', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beleg', to='rechnungen.rechnung')),
            ],
            options={
                'verbose_name': 'Beleg',
                'verbose_name_plural': 'Belege',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
