# Generated by Django 5.1 on 2026-08-03 12:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumente', '0002_add_beleg_belegnummerzaehler'),
        ('objekte', '0021_alter_objekt_auto_pipeline_aktiv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='abgelegt_am',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dokument',
            name='beleg_nummer',
            field=models.CharField(blank=True, editable=False, help_text='Globale Belegnummer (AA00000001 …), Vergabe über BelegnummerZaehler', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dokument',
            name='dokument_typ',
            field=models.CharField(choices=[('beleg', 'Beleg'), ('vertrag', 'Vertrag'), ('korrespondenz', 'Korrespondenz'), ('beschluss', 'Beschluss'), ('abrechnung', 'Abrechnung'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=20),
        ),
        migrations.AddField(
            model_name='dokument',
            name='revisionssicher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokument',
            name='revisionssicher_seit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dokument',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='einheit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dokumente', to='objekte.einheit'),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='objekt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dokumente', to='objekte.objekt'),
        ),
    ]
