# Generated by Django 5.1 on 2026-08-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumente', '0003_dokument_abgelegt_am_dokument_beleg_nummer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='ablage_wurzel',
            field=models.CharField(choices=[('media', 'MEDIA_ROOT'), ('rechnungen', 'Rechnungen-Bind-Mount')], default='media', help_text='Wurzel, unter der datei relativ aufgelöst wird — Zugriff nur über beleg_service.dokument_pfad()', max_length=20),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='datei',
            field=models.FileField(max_length=1000, upload_to='dokumente/'),
        ),
    ]
