# Generated by Django 5.1 on 2026-08-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokumente', '0004_dokument_ablage_wurzel_alter_dokument_datei'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beleg',
        ),
    ]
