# Generated by Django 5.1 on 2026-08-08 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumente', '0005_delete_beleg'),
        ('personen', '0019_person_emails_telefonnummern'),
        ('vorgaenge', '0002_seed_vorgangtyp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dokumente', to='personen.person'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dokument',
            name='vorgaenger_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nachfolger_versionen', to='dokumente.dokument'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='vorgang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dokumente', to='vorgaenge.vorgang'),
        ),
    ]
