# Generated by Django 5.1 on 2026-08-08 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumente', '0007_beleg_dokumente_kontext_bereinigen'),
        ('objekte', '0021_alter_objekt_auto_pipeline_aktiv_and_more'),
        ('personen', '0019_person_emails_telefonnummern'),
        ('vorgaenge', '0002_seed_vorgangtyp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dokument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('objekt__isnull', False), ('einheit__isnull', False), _negated=True), models.Q(('objekt__isnull', False), ('vorgang__isnull', False), _negated=True), models.Q(('objekt__isnull', False), ('person__isnull', False), _negated=True), models.Q(('einheit__isnull', False), ('vorgang__isnull', False), _negated=True), models.Q(('einheit__isnull', False), ('person__isnull', False), _negated=True), models.Q(('vorgang__isnull', False), ('person__isnull', False), _negated=True)), name='dokument_max_ein_kontext'),
        ),
    ]
