# Generated by Django 5.1 on 2026-08-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokumente', '0008_dokument_dokument_max_ein_kontext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokument',
            name='verknuepfung_typ',
        ),
    ]
