# Generated by Django 5.1 on 2026-09-14 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumente', '0009_entferne_verknuepfung_typ'),
        ('vorgaenge', '0010_mailimportprotokoll_bezug_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='mail_import',
            field=models.ForeignKey(blank=True, help_text='Herkunft: aus dieser eingegangenen Mail stammt das Dokument (die Mail selbst oder einer ihrer Anhaenge). Bewusst KEIN Kontext-FK im Sinne der Owner-Regel — es sagt, WOHER das Dokument kam, nicht WOZU es gehoert. Der Kontext wird nachgetragen, sobald die Mail im Posteingang zugeordnet wird.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumente', to='vorgaenge.mailimportprotokoll'),
        ),
    ]
