# Generated by Django 5.1 on 2026-09-15 09:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumente', '0010_dokument_mail_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='dokument_datum',
            field=models.DateField(blank=True, help_text='Das FACHLICHE Datum: wann die Mail gesendet, die Rechnung gestellt, der Vertrag geschlossen wurde — nicht wann die Datei abgelegt wurde. Entscheidet in der Eigentuemerakte darueber, in wessen Besitzzeit ein Dokument faellt; ohne Angabe gilt ersatzweise das Ablagedatum, was bei spaet nachgereichten Altunterlagen falsch liegen kann.', null=True, verbose_name='Datum des Dokuments'),
        ),
        migrations.CreateModel(
            name='Aktenregister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Kurzzeichen der Ablage, z.B. "04" oder "04.1". Wird beim Import aus einer Ordnerstruktur zum Wiedererkennen genutzt.', max_length=20, unique=True)),
                ('bezeichnung', models.CharField(max_length=120)),
                ('aktenart', models.CharField(choices=[('haus', 'Hausakte'), ('wohnung', 'Wohnungsakte'), ('eigentuemer', 'Eigentuemerakte'), ('alle', 'In allen Akten')], default='haus', max_length=12)),
                ('sortierung', models.IntegerField(default=0)),
                ('aktiv', models.BooleanField(default=True, help_text='Inaktive Register verschwinden aus der Auswahl, die darin bereits abgelegten Dokumente bleiben unberuehrt.')),
                ('hinweis', models.TextField(blank=True, default='', help_text='Was gehoert hier hinein — erscheint als Hilfetext an der Ablagemaske.')),
                ('eltern', models.ForeignKey(blank=True, help_text='Leer = Register oberster Ebene.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unterregister', to='dokumente.aktenregister')),
            ],
            options={
                'verbose_name': 'Aktenregister',
                'verbose_name_plural': 'Aktenregister',
                'ordering': ['sortierung', 'code'],
            },
        ),
        migrations.AddField(
            model_name='dokument',
            name='register',
            field=models.ForeignKey(blank=True, help_text='Einordnung in die Aktengliederung. Leer = noch nicht einsortiert; solche Dokumente sammelt die Aktenansicht unter "Ohne Register", damit nichts unsichtbar wird.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dokumente', to='dokumente.aktenregister'),
        ),
    ]
