# Generated by Django 5.1 on 2026-09-20 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumente', '0011_dokument_dokument_datum_aktenregister_and_more'),
        ('objekte', '0022_objekt_handwerker'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktenregister',
            name='objekt',
            field=models.ForeignKey(blank=True, help_text='Leer = gilt fuer ALLE Akten (die gemeinsame Gliederung). Gesetzt = nur in der Akte dieses Objekts sichtbar — das digitale Gegenstueck zum Trennblatt, das bei Bedarf in genau einen Ordner gelegt wird ("05/A Hebeanlage"). CASCADE: verschwindet das Objekt, verschwindet auch seine eigene Untergliederung.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aktenregister', to='objekte.objekt'),
        ),
        migrations.AlterField(
            model_name='aktenregister',
            name='code',
            field=models.CharField(help_text='Kurzzeichen der Ablage, z.B. "05" oder "05/A". Wird beim Import aus einer Ordnerstruktur zum Wiedererkennen genutzt. Nur zusammen mit objekt eindeutig — derselbe Code darf in zwei Objekten fuer Verschiedenes stehen.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='aktenregister',
            constraint=models.UniqueConstraint(fields=('code', 'objekt'), name='uniq_register_code_je_objekt'),
        ),
        migrations.AddConstraint(
            model_name='aktenregister',
            constraint=models.UniqueConstraint(condition=models.Q(('objekt__isnull', True)), fields=('code',), name='uniq_register_code_global'),
        ),
    ]
