# Generated by Django 5.1 on 2026-09-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumente', '0013_seed_aktenregister_hausakte'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='titel',
            field=models.CharField(blank=True, default='', help_text='Sprechender Anzeigename. Der DATEINAME bleibt davon unberuehrt — er ist die Bruecke zur Datei im Archivordner, gehoert bei revisionssicheren Belegen zur Nachvollziehbarkeit und ist der Name, unter dem der Absender sein Dokument kennt. Leer = es wird der Dateiname angezeigt (siehe anzeigename).', max_length=200),
        ),
    ]
