# Generated by Django 5.1 on 2026-09-29 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buchhaltung', '0058_alter_frontofficeaufgabe_aufgabe_typ'),
        ('dokumente', '0015_titel_fuer_bestandsmails'),
        ('objekte', '0023_objekt_mailversand_aktiv'),
        ('personen', '0022_person_zustellweg_person_zustellweg_zustimmung_am'),
        ('vorgaenge', '0015_alter_vorgangereignis_typ'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchreibenNummerZaehler',
            fields=[
                ('jahr', models.IntegerField(primary_key=True, serialize=False)),
                ('letzter_zaehler', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Schreiben-Nummer-Zähler',
                'verbose_name_plural': 'Schreiben-Nummer-Zähler',
            },
        ),
        migrations.CreateModel(
            name='Briefbogen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bezeichnung', models.CharField(max_length=100)),
                ('firma_name', models.CharField(max_length=200)),
                ('firma_strasse', models.CharField(blank=True, max_length=200)),
                ('firma_plz', models.CharField(blank=True, max_length=10)),
                ('firma_ort', models.CharField(blank=True, max_length=100)),
                ('telefon', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('web', models.CharField(blank=True, max_length=200)),
                ('sprechzeiten', models.TextField(blank=True)),
                ('hinweis_infoblock', models.TextField(blank=True)),
                ('fuss_firma_zeile1', models.CharField(blank=True, max_length=200)),
                ('fuss_firma_zeile2', models.CharField(blank=True, max_length=200)),
                ('fuss_firma_zeile3', models.CharField(blank=True, max_length=200)),
                ('pflichtangaben', models.CharField(blank=True, max_length=300)),
                ('steuerzeichen_unsichtbar', models.CharField(blank=True, max_length=50)),
                ('ist_standard', models.BooleanField(default=False)),
                ('aktiv', models.BooleanField(default=True)),
                ('fuss_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dokumente.dokument')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dokumente.dokument')),
            ],
            options={
                'verbose_name': 'Briefbogen',
                'verbose_name_plural': 'Briefbögen',
                'ordering': ['bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='Vorlage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('bezeichnung', models.CharField(max_length=150)),
                ('anlass', models.CharField(choices=[('eigentuemer_begruessung', 'Begrüßung neuer Eigentümer'), ('eigentuemer_verabschiedung', 'Verabschiedung Voreigentümer'), ('mahnung_stufe_1', 'Mahnung Stufe 1 (Zahlungserinnerung)'), ('mahnung_stufe_2', 'Mahnung Stufe 2'), ('mahnung_stufe_3', 'Mahnung Stufe 3 (letzte Mahnung)'), ('etv_einladung', 'Einladung Eigentümerversammlung'), ('eigentuemer_allgemein', 'Allgemeines Eigentümerschreiben'), ('vorgang_antwort', 'Vorgangsantwort')], max_length=40)),
                ('kanal_standard', models.CharField(choices=[('brief', 'Brief'), ('email', 'E-Mail'), ('beides', 'Brief und E-Mail')], default='brief', max_length=10)),
                ('einzeln_bearbeitbar', models.BooleanField(default=False)),
                ('aktiv', models.BooleanField(default=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('briefbogen', models.ForeignKey(blank=True, help_text='Leer = Standard-Briefbogen.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vorlagen', to='korrespondenz.briefbogen')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_korrespondenz_vorlagen', to=settings.AUTH_USER_MODEL)),
                ('objekt', models.ForeignKey(blank=True, help_text='Leer = globale Vorlage; gesetzt = objektspezifische Übersteuerung.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='korrespondenz_vorlagen', to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Vorlage',
                'verbose_name_plural': 'Vorlagen',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VorlageAnlage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('art', models.CharField(choices=[('dokument', 'Festes PDF-Dokument'), ('objekt_kategorie', 'Objektbezogenes Dokument (Kategorie)')], max_length=20)),
                ('bezeichnung', models.CharField(max_length=150)),
                ('pflicht', models.BooleanField(default=False)),
                ('reihenfolge', models.PositiveIntegerField(default=0)),
                ('vorlage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anlagen', to='korrespondenz.vorlage')),
            ],
            options={
                'verbose_name': 'Vorlagen-Anlage',
                'verbose_name_plural': 'Vorlagen-Anlagen',
                'ordering': ['vorlage', 'reihenfolge'],
            },
        ),
        migrations.CreateModel(
            name='VorlagenVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('betreff', models.CharField(max_length=250)),
                ('inhalt', models.JSONField(default=list, help_text='Blockstruktur, siehe Spec 3.4.')),
                ('email_begleittext', models.TextField(blank=True)),
                ('eingabefelder', models.JSONField(blank=True, default=list, help_text='Spec 3.5.')),
                ('pflicht_platzhalter', models.JSONField(blank=True, default=list)),
                ('parameter', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('freigegeben', 'Freigegeben'), ('abgeloest', 'Abgelöst')], default='entwurf', max_length=15)),
                ('freigegeben_am', models.DateTimeField(blank=True, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_korrespondenz_versionen', to=settings.AUTH_USER_MODEL)),
                ('freigegeben_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freigegebene_korrespondenz_versionen', to=settings.AUTH_USER_MODEL)),
                ('vorlage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versionen', to='korrespondenz.vorlage')),
            ],
            options={
                'verbose_name': 'Vorlagen-Version',
                'verbose_name_plural': 'Vorlagen-Versionen',
                'ordering': ['vorlage', '-version'],
                'permissions': [('vorlage_freigeben', 'Darf Vorlagenversionen freigeben')],
            },
        ),
        migrations.AddField(
            model_name='vorlage',
            name='aktive_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='korrespondenz.vorlagenversion'),
        ),
        migrations.CreateModel(
            name='Serienlauf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empfaenger_filter', models.JSONField(blank=True, default=dict)),
                ('eingabewerte', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('vorschau', 'Vorschau'), ('zur_pruefung', 'Zur Prüfung'), ('freigegeben', 'Freigegeben'), ('versendet', 'Versendet'), ('teilweise_fehler', 'Teilweise Fehler')], default='vorschau', max_length=20)),
                ('anzahl', models.PositiveIntegerField(default=0)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('freigegeben_am', models.DateTimeField(blank=True, null=True)),
                ('druck_dokument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dokumente.dokument')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_serienlaeufe', to=settings.AUTH_USER_MODEL)),
                ('freigegeben_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freigegebene_serienlaeufe', to=settings.AUTH_USER_MODEL)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='korrespondenz_serienlaeufe', to='objekte.objekt')),
                ('unterzeichner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unterzeichnete_serienlaeufe', to=settings.AUTH_USER_MODEL)),
                ('vorlage_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serienlaeufe', to='korrespondenz.vorlagenversion')),
            ],
            options={
                'verbose_name': 'Serienlauf',
                'verbose_name_plural': 'Serienläufe',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='Schreiben',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nummer', models.CharField(editable=False, max_length=20, unique=True)),
                ('ihr_zeichen', models.CharField(blank=True, max_length=100)),
                ('ihr_schreiben_vom', models.DateField(blank=True, null=True)),
                ('eingabewerte', models.JSONField(blank=True, default=dict)),
                ('kanal', models.CharField(choices=[('brief', 'Brief'), ('email', 'E-Mail')], default='brief', max_length=10)),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('zur_pruefung', 'Zur Prüfung'), ('freigegeben', 'Freigegeben'), ('versendet', 'Versendet'), ('verworfen', 'Verworfen'), ('versand_fehlgeschlagen', 'Versand fehlgeschlagen')], default='entwurf', max_length=25)),
                ('inhalt_angepasst', models.JSONField(blank=True, null=True)),
                ('html_gerendert', models.TextField(blank=True)),
                ('kontext_snapshot', models.JSONField(blank=True, default=dict)),
                ('freigegeben_am', models.DateTimeField(blank=True, null=True)),
                ('versendet_am', models.DateTimeField(blank=True, null=True)),
                ('mail_message_id', models.CharField(blank=True, max_length=255)),
                ('fehler', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('dokument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='korrespondenz_schreiben', to='dokumente.dokument')),
                ('eigentuemerwechsel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='korrespondenz_schreiben', to='buchhaltung.eigentuemerwechselvorgang')),
                ('eigentumsverhaeltnis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='korrespondenz_schreiben', to='personen.eigentumsverhaeltnis')),
                ('einheit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='korrespondenz_schreiben', to='objekte.einheit')),
                ('empfaenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='korrespondenz_schreiben', to='personen.person')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_schreiben', to=settings.AUTH_USER_MODEL)),
                ('freigegeben_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freigegebene_schreiben', to=settings.AUTH_USER_MODEL)),
                ('mahnung', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='korrespondenz_schreiben', to='buchhaltung.mahnung')),
                ('objekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='korrespondenz_schreiben', to='objekte.objekt')),
                ('unterzeichner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unterzeichnete_schreiben', to=settings.AUTH_USER_MODEL)),
                ('vorgang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='korrespondenz_schreiben', to='vorgaenge.vorgang')),
                ('serienlauf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schreiben', to='korrespondenz.serienlauf')),
                ('vorlage_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schreiben', to='korrespondenz.vorlagenversion')),
            ],
            options={
                'verbose_name': 'Schreiben',
                'verbose_name_plural': 'Schreiben',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='Textbaustein',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('bezeichnung', models.CharField(max_length=150)),
                ('inhalt', models.TextField()),
                ('aktiv', models.BooleanField(default=True)),
                ('objekt', models.ForeignKey(blank=True, help_text='Leer = global.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='korrespondenz_textbausteine', to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Textbaustein',
                'verbose_name_plural': 'Textbausteine',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('code', 'objekt'), name='korr_baustein_code_objekt_uniq'), models.UniqueConstraint(condition=models.Q(('objekt__isnull', True)), fields=('code',), name='korr_baustein_code_global_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='vorlagenversion',
            constraint=models.UniqueConstraint(fields=('vorlage', 'version'), name='korr_version_vorlage_nr_uniq'),
        ),
        migrations.AddConstraint(
            model_name='vorlage',
            constraint=models.UniqueConstraint(fields=('code', 'objekt'), name='korr_vorlage_code_objekt_uniq'),
        ),
        migrations.AddConstraint(
            model_name='vorlage',
            constraint=models.UniqueConstraint(condition=models.Q(('objekt__isnull', True)), fields=('code',), name='korr_vorlage_code_global_uniq'),
        ),
        migrations.AddConstraint(
            model_name='schreiben',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('eigentuemerwechsel__isnull', True), ('mahnung__isnull', True)), models.Q(('mahnung__isnull', True), ('serienlauf__isnull', True)), models.Q(('eigentuemerwechsel__isnull', True), ('serienlauf__isnull', True)), _connector='OR'), name='korr_schreiben_max_ein_kontext'),
        ),
    ]
