# Generated by Django 5.1 on 2026-09-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korrespondenz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefbogen',
            name='pflichtangaben_anzeigen',
            field=models.BooleanField(default=True, help_text='GmbH-Pflichtangaben (§ 35a GmbHG) als 6-pt-Zeile unter der WEG-Bankverbindung drucken (Spec 5.4).'),
        ),
    ]
