# Generated by Django 5.1 on 2026-09-29 19:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumente', '0015_titel_fuer_bestandsmails'),
        ('korrespondenz', '0002_briefbogen_pflichtangaben_anzeigen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Druckstapel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('bestaetigt', 'Bestätigt')], default='offen', max_length=15)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('bestaetigt_am', models.DateTimeField(blank=True, null=True)),
                ('bestaetigt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bestaetigte_druckstapel', to=settings.AUTH_USER_MODEL)),
                ('dokument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dokumente.dokument')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_druckstapel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Druckstapel',
                'verbose_name_plural': 'Druckstapel',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.AddField(
            model_name='schreiben',
            name='druckstapel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schreiben', to='korrespondenz.druckstapel'),
        ),
    ]
