# Generated by Django 5.1 on 2026-09-29 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumente', '0015_titel_fuer_bestandsmails'),
        ('korrespondenz', '0003_druckstapel_schreiben_druckstapel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vorlageanlage',
            name='dokument',
            field=models.ForeignKey(blank=True, help_text='Festes PDF (nur bei art="dokument").', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dokumente.dokument'),
        ),
        migrations.AddField(
            model_name='vorlageanlage',
            name='objekt_kategorie',
            field=models.CharField(blank=True, help_text='Dokumentkategorie des Objekts (nur bei art="objekt_kategorie"), z. B. Hausordnung.', max_length=100),
        ),
    ]
