# Generated by Django 5.1 on 2026-09-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korrespondenz', '0005_vorlageanlage_bedingung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serienlauf',
            name='status',
            field=models.CharField(choices=[('vorschau', 'Vorschau'), ('zur_pruefung', 'Zur Prüfung'), ('freigegeben', 'Freigegeben'), ('versendet', 'Versendet'), ('teilweise_fehler', 'Teilweise Fehler'), ('abgebrochen', 'Abgebrochen')], default='vorschau', max_length=20),
        ),
    ]
