# Generated by Django 5.2.12 on 2026-05-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitarbeiter', '0003_mitarbeiterobjektzuordnung_aufgabe'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='abwesend',
            field=models.BooleanField(default=False, verbose_name='Abwesend (Vertretung aktiv)'),
        ),
        migrations.AlterField(
            model_name='mitarbeiterobjektzuordnung',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
