# Generated by Django 5.1 on 2026-07-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitarbeiter', '0004_add_abwesend'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='freigabe_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Persönliches Freigabelimit. NULL = keine Freigabeberechtigung. Rechnung darf freigegeben werden, wenn betrag_brutto <= freigabe_limit (Umbau Rechnungseingang v1.0, Spec Kap. 3.2 / V9).', max_digits=12, null=True, verbose_name='Freigabelimit (EUR)'),
        ),
    ]
