# Generated by Django 5.1 on 2026-07-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitarbeiter', '0005_mitarbeiter_freigabe_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitarbeiter',
            name='freigabe_limit',
        ),
    ]
