# Generated by Django 5.2.12 on 2026-04-03 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('konten', '0001_initial'),
        ('objekte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buchung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=12)),
                ('belegnr', models.CharField(blank=True, max_length=50)),
                ('buchungsdatum', models.DateField()),
                ('wertstellungsdatum', models.DateField(blank=True, null=True)),
                ('verwendungszweck', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('vorerfasst', 'Vorerfasst'), ('gebucht', 'Gebucht'), ('storniert', 'Storniert')], default='vorerfasst', max_length=20)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buchungen', to=settings.AUTH_USER_MODEL)),
                ('haben_konto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='haben_buchungen', to='konten.konto')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buchungen', to='objekte.objekt')),
                ('soll_konto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soll_buchungen', to='konten.konto')),
                ('unterkonto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buchungen', to='konten.unterkonto')),
            ],
            options={
                'verbose_name': 'Buchung',
                'verbose_name_plural': 'Buchungen',
                'ordering': ['-buchungsdatum', '-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='BankImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha256_hash', models.CharField(max_length=64, unique=True)),
                ('auftraggeber_name', models.CharField(blank=True, max_length=255)),
                ('auftraggeber_iban', models.CharField(blank=True, max_length=34)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buchungsdatum', models.DateField()),
                ('wertstellungsdatum', models.DateField(blank=True, null=True)),
                ('verwendungszweck', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('neu', 'Neu'), ('erkannt', 'Erkannt'), ('manuell', 'Manuell'), ('ignoriert', 'Ignoriert')], default='neu', max_length=20)),
                ('ki_vorschlag', models.JSONField(blank=True, null=True)),
                ('importiert_am', models.DateTimeField(auto_now_add=True)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_importe', to='objekte.objekt')),
                ('buchung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_importe', to='buchhaltung.buchung')),
            ],
            options={
                'verbose_name': 'Bank-Import',
                'verbose_name_plural': 'Bank-Importe',
                'ordering': ['-buchungsdatum', '-importiert_am'],
            },
        ),
        migrations.CreateModel(
            name='Jahresabrechnung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wirtschaftsjahr', models.IntegerField()),
                ('erstellungsdatum', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('freigegeben', 'Freigegeben'), ('gesperrt', 'Gesperrt')], default='entwurf', max_length=20)),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jahresabrechnungen', to=settings.AUTH_USER_MODEL)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jahresabrechnungen', to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Jahresabrechnung',
                'verbose_name_plural': 'Jahresabrechnungen',
                'ordering': ['-wirtschaftsjahr'],
                'unique_together': {('objekt', 'wirtschaftsjahr')},
            },
        ),
        migrations.CreateModel(
            name='EinzelAbrechnung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eigentuemer_snapshot', models.JSONField()),
                ('hausgeld_soll_gesamt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kostenanteil_gesamt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('abrechnungsergebnis', models.DecimalField(decimal_places=2, max_digits=12)),
                ('positionen', models.JSONField(default=list)),
                ('ruecklagen', models.JSONField(default=list)),
                ('pdf_pfad', models.CharField(blank=True, max_length=500)),
                ('gebucht', models.BooleanField(default=False)),
                ('einheit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='einzelabrechnungen', to='objekte.einheit')),
                ('personenkonto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='einzelabrechnungen', to='konten.personenkonto')),
                ('jahresabrechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einzelabrechnungen', to='buchhaltung.jahresabrechnung')),
            ],
            options={
                'verbose_name': 'Einzelabrechnung',
                'verbose_name_plural': 'Einzelabrechnungen',
                'ordering': ['jahresabrechnung', 'einheit__einheit_nr'],
            },
        ),
    ]
