# Generated by Django 5.2.12 on 2026-04-23 18:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0005_buchung_soll_unterkonto'),
        ('objekte', '0011_remove_vs101'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buchungsstapel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bezeichnung', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('ausgebucht', 'Ausgebucht')], default='offen', max_length=20)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('ausgebucht_am', models.DateTimeField(blank=True, null=True)),
                ('ausgebucht_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausgebuchte_stapel', to=settings.AUTH_USER_MODEL)),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buchungsstapel', to=settings.AUTH_USER_MODEL)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buchungsstapel', to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Buchungsstapel',
                'verbose_name_plural': 'Buchungsstapel',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.AddField(
            model_name='buchung',
            name='stapel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buchungen', to='buchhaltung.buchungsstapel'),
        ),
    ]
