# Generated by Django 5.2.12 on 2026-04-23 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0006_buchungsstapel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sollstellung',
            name='buchungsart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sollstellungen', to='buchhaltung.buchungsart'),
        ),
    ]
