# Generated by Django 5.1 on 2026-04-23 18:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0007_sollstellung_buchungsart_nullable'),
        ('objekte', '0011_remove_vs101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportOrdnerEinstellung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bereich', models.CharField(choices=[('rechnungen', 'Rechnungen'), ('dokumente', 'Dokumente')], max_length=50)),
                ('import_ordner', models.CharField(blank=True, max_length=500)),
                ('archiv_ordner', models.CharField(blank=True, max_length=500)),
                ('fehler_ordner', models.CharField(blank=True, max_length=500)),
                ('aktiv', models.BooleanField(default=True)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_ordner_einstellungen', to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Import-Ordner-Einstellung',
                'verbose_name_plural': 'Import-Ordner-Einstellungen',
                'unique_together': {('bereich', 'objekt')},
            },
        ),
    ]
