# Generated by Django 5.1 on 2026-05-24 17:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0014_kreditor_op'),
        ('objekte', '0014_datenmigration_betreuer'),
        ('rechnungen', '0011_wkz_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kreditorop',
            name='herkunft',
            field=models.CharField(choices=[('eingangsrechnung', 'Eingangsrechnung'), ('wkz_vorlage', 'Wiederkehrende Buchung'), ('manuell', 'Manuell')], default='eingangsrechnung', max_length=20),
        ),
        migrations.AddField(
            model_name='kreditorop',
            name='verwendungszweck',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kreditorop',
            name='buchung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kreditor_op_erstellung', to='buchhaltung.buchung'),
        ),
        migrations.AlterField(
            model_name='kreditorop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='WiederkehrendeBuchungVorlage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bezeichnung', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('bescheid', 'Bescheid'), ('vertrag', 'Vertrag')], max_length=10)),
                ('betrag_gesamt', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rhythmus', models.CharField(choices=[('monatlich', 'Monatlich'), ('zweimonatlich', 'Zweimonatlich'), ('quartalsweise', 'Quartalsweise'), ('halbjaehrlich', 'Halbjährlich'), ('jaehrlich', 'Jährlich'), ('frei', 'Frei (manuell)')], max_length=15)),
                ('erste_faelligkeit', models.DateField()),
                ('bei_wochenende', models.CharField(choices=[('vor', 'Vorverschieben (Freitag)'), ('zurueck', 'Zurückverschieben (Montag)'), ('unveraendert', 'Unverändert')], default='zurueck', max_length=12)),
                ('vorlauf_tage', models.IntegerField(default=7)),
                ('toleranz_betrag', models.DecimalField(decimal_places=2, default='5.00', max_digits=14)),
                ('toleranz_tage', models.IntegerField(default=14)),
                ('sepa_mandat_id', models.CharField(blank=True, max_length=35)),
                ('bescheid_pflicht', models.BooleanField(default=True)),
                ('gueltig_ab', models.DateField()),
                ('gueltig_bis', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('aktiv', 'Aktiv'), ('pausiert', 'Pausiert'), ('beendet', 'Beendet')], default='entwurf', max_length=10)),
                ('freigegeben_am', models.DateTimeField(blank=True, null=True)),
                ('freigabe_jahresbetrag', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('ersetzt_vorlage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nachfolger_vorlagen', to='buchhaltung.wiederkehrendebuchungvorlage')),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_wkz_vorlagen', to=settings.AUTH_USER_MODEL)),
                ('freigegeben_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freigegebene_wkz_vorlagen', to=settings.AUTH_USER_MODEL)),
                ('kreditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wkz_vorlagen', to='rechnungen.kreditor')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wkz_vorlagen', to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Wiederkehrende Buchung (Vorlage)',
                'verbose_name_plural': 'Wiederkehrende Buchungen (Vorlagen)',
                'ordering': ['objekt', 'bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='WiederkehrendeBuchungSplit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kontonummer', models.CharField(max_length=8)),
                ('bezeichnung', models.CharField(max_length=200)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reihenfolge', models.PositiveIntegerField(default=0)),
                ('vorlage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='buchhaltung.wiederkehrendebuchungvorlage')),
            ],
            options={
                'verbose_name': 'WKZ-Split',
                'verbose_name_plural': 'WKZ-Splits',
                'ordering': ['reihenfolge', 'kontonummer'],
            },
        ),
        migrations.CreateModel(
            name='WiederkehrendeBuchungOP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode_von', models.DateField()),
                ('periode_bis', models.DateField()),
                ('faellig_am', models.DateField()),
                ('erzeugt_am', models.DateTimeField(auto_now_add=True)),
                ('bescheid_hochgeladen_am', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('erzeugt', 'Erzeugt'), ('bescheid_fehlt', 'Bescheid fehlt'), ('bankabgang_erfolgt', 'Bankabgang erfolgt'), ('abweichend_geklaert', 'Abweichend (geklärt)'), ('verworfen', 'Verworfen')], default='erzeugt', max_length=22)),
                ('abweichung_betrag', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('klaerungs_grund', models.TextField(blank=True)),
                ('bank_match_buchung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wkz_ops', to='buchhaltung.buchung')),
                ('bescheid_hochgeladen_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wkz_bescheid_uploads', to=settings.AUTH_USER_MODEL)),
                ('kreditor_op', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wkz_op', to='buchhaltung.kreditorop')),
                ('vorlage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops', to='buchhaltung.wiederkehrendebuchungvorlage')),
            ],
            options={
                'verbose_name': 'WKZ-OP',
                'verbose_name_plural': 'WKZ-OPs',
                'ordering': ['-faellig_am'],
            },
        ),
        migrations.AddConstraint(
            model_name='wiederkehrendebuchungvorlage',
            constraint=models.CheckConstraint(condition=models.Q(('betrag_gesamt__gt', 0)), name='wkz_vorlage_betrag_positiv'),
        ),
        migrations.AddConstraint(
            model_name='wiederkehrendebuchungvorlage',
            constraint=models.CheckConstraint(condition=models.Q(('gueltig_bis__isnull', True), ('gueltig_bis__gte', models.F('gueltig_ab')), _connector='OR'), name='wkz_vorlage_gueltig_bis_nach_ab'),
        ),
        migrations.AddConstraint(
            model_name='wiederkehrendebuchungsplit',
            constraint=models.CheckConstraint(condition=models.Q(('betrag__gt', 0)), name='wkz_split_betrag_positiv'),
        ),
        migrations.AddConstraint(
            model_name='wiederkehrendebuchungop',
            constraint=models.UniqueConstraint(fields=('vorlage', 'periode_von', 'periode_bis'), name='wkz_op_unique_periode_je_vorlage'),
        ),
    ]
