# Generated by Django 5.1 on 2026-05-10 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0019_lastschriftlauf_hg_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sollstellungslauf',
            name='ausgefuehrt_von',
        ),
        migrations.RemoveField(
            model_name='sollstellungslauf',
            name='freigabe_user',
        ),
        migrations.RemoveField(
            model_name='sollstellungslauf',
            name='objekt',
        ),
        migrations.RemoveField(
            model_name='lastschriftlauf',
            name='sollstellungs_lauf',
        ),
        migrations.AlterModelOptions(
            name='hausgeldsollstellung',
            options={'ordering': ['-periode', 'eigentumsverhaeltnis'], 'verbose_name': 'Hausgeld-Sollstellung', 'verbose_name_plural': 'Hausgeld-Sollstellungen'},
        ),
        migrations.AlterModelOptions(
            name='hausgeldsollstellungslauf',
            options={'ordering': ['-periode', 'objekt'], 'verbose_name': 'Hausgeld-Sollstellungslauf', 'verbose_name_plural': 'Hausgeld-Sollstellungsläufe'},
        ),
        migrations.AlterModelOptions(
            name='opossequenz',
            options={'verbose_name': 'OPOS-Sequenz', 'verbose_name_plural': 'OPOS-Sequenzen'},
        ),
        migrations.AlterModelOptions(
            name='sollstellungsplit',
            options={'verbose_name': 'Sollstellungs-Split', 'verbose_name_plural': 'Sollstellungs-Splits'},
        ),
        migrations.AlterModelOptions(
            name='sollstellungzahlung',
            options={'ordering': ['erstellt_am'], 'verbose_name': 'Sollstellungs-Zahlung', 'verbose_name_plural': 'Sollstellungs-Zahlungen'},
        ),
        migrations.AlterField(
            model_name='buchungsart',
            name='bankkonto_typ',
            field=models.CharField(blank=True, choices=[('bewirtschaftung', 'Bewirtschaftungskonto'), ('ruecklage_nach_index', 'Rücklage nach Konto-Index'), ('frei', 'Frei konfigurierbar')], help_text='Routing-Hinweis für den Lastschriftlauf.', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='buchungsart',
            name='erloeskonto_default_nr',
            field=models.CharField(blank=True, help_text='Kontonummer des Erlöskontos (z.B. 41900). Wird beim Sollstellungslauf aufgelöst.', max_length=10, verbose_name='Standard-Erlöskonto (Kontonummer)'),
        ),
        migrations.AlterField(
            model_name='buchungsart',
            name='tilgungs_prioritaet',
            field=models.IntegerField(blank=True, help_text='Kleinere Zahl = höhere Priorität. NULL = keine Tilgungs-Priorisierung.', null=True),
        ),
        migrations.AlterField(
            model_name='hausgeldsollstellung',
            name='ba',
            field=models.ForeignKey(blank=True, help_text='NULL bei hausgeld; gesetzt bei sonderumlage/abrechnungsergebnis', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='buchhaltung.buchungsart'),
        ),
        migrations.AlterField(
            model_name='hausgeldsollstellungslauf',
            name='status',
            field=models.CharField(choices=[('vorschau', 'Vorschau'), ('freigegeben', 'Freigegeben (Vier-Augen)'), ('commited', 'Commited / Ausgeführt'), ('storniert', 'Storniert')], default='vorschau', max_length=20),
        ),
        migrations.AlterField(
            model_name='hausgeldsollstellungslauf',
            name='typ',
            field=models.CharField(choices=[('hausgeld_monat', 'Hausgeld monatlich'), ('sonderumlage', 'Sonderumlage'), ('abrechnungsergebnis_jahr', 'Abrechnungsergebnis Wirtschaftsjahr')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Sollstellung',
        ),
        migrations.DeleteModel(
            name='SollstellungsLauf',
        ),
    ]
