# Generated by Django 5.1 on 2026-05-13 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0023_camtimporteinstellung_objekt'),
        ('objekte', '0017_objekt_kurzbezeichnung'),
    ]

    operations = [
        migrations.AddField(
            model_name='hausgeldsollstellungslauf',
            name='fehler_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='kontoumsatz',
            name='status',
            field=models.CharField(choices=[('importiert', 'Importiert'), ('erkannt', 'Erkannt (KI-Vorschlag)'), ('manuell', 'Manuell zugeordnet'), ('gebucht', 'Gebucht'), ('ignoriert', 'Ignoriert'), ('unbekannt', 'Unbekannt (kein Objekt)')], default='importiert', max_length=12),
        ),
        migrations.AlterField(
            model_name='sollstellungsplit',
            name='bankkonto_ziel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='objekte.bankkonto'),
        ),
    ]
