# Generated by Django 5.1 on 2026-05-14 16:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0026_auto_pipeline_models'),
        ('objekte', '0018_objekt_auto_pipeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontofficeAufgabe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aufgabe_typ', models.CharField(choices=[('kein_sepa_mandat', 'SEPA-Mandat fehlt'), ('keine_iban', 'Keine IBAN hinterlegt'), ('keine_hausgeldhistorie', 'Kein Hausgeldsatz'), ('mandat_typ_frst', 'Erst-Mandat (FRST)'), ('sepa_frist_unterschritten', 'SEPA-Frist unterschritten'), ('dateischreibfehler', 'Dateischreibfehler')], max_length=40)),
                ('beschreibung', models.TextField()),
                ('ev_id', models.UUIDField(blank=True, null=True)),
                ('einheit_nr', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('in_bearbeitung', 'In Bearbeitung'), ('erledigt', 'Erledigt')], default='offen', max_length=20)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('erledigt_am', models.DateTimeField(blank=True, null=True)),
                ('lock_expires_at', models.DateTimeField(blank=True, null=True)),
                ('erledigt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erledigte_frontoffice_aufgaben', to=settings.AUTH_USER_MODEL)),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_frontoffice_aufgaben', to=settings.AUTH_USER_MODEL)),
                ('lock_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontoffice_locks', to=settings.AUTH_USER_MODEL)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frontoffice_aufgaben', to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Frontoffice-Aufgabe',
                'verbose_name_plural': 'Frontoffice-Aufgaben',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
