# Generated by Django 5.1 on 2026-05-15 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0027_frontoffice_aufgabe'),
    ]

    operations = [
        migrations.AddField(
            model_name='hausgeldsollstellung',
            name='korrektur_grund',
            field=models.CharField(blank=True, choices=[('eigentuemerwechsel', 'Eigentümerwechsel'), ('wirtschaftsplan_aenderung', 'Wirtschaftsplan-Änderung')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='hausgeldsollstellung',
            name='korrektur_vorgang_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hausgeldsollstellung',
            name='neutralisiert_durch_opos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='buchhaltung.hausgeldsollstellung'),
        ),
        migrations.AddField(
            model_name='hausgeldsollstellung',
            name='neutralisiert_opos_nr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='buchhaltung.hausgeldsollstellung'),
        ),
        migrations.AlterField(
            model_name='hausgeldsollstellung',
            name='sollstellungs_typ',
            field=models.CharField(choices=[('hausgeld', 'Hausgeld'), ('sonderumlage', 'Sonderumlage'), ('abrechnungsergebnis', 'Abrechnungsergebnis'), ('korrektur', 'Korrektur')], max_length=20),
        ),
    ]
