# Generated by Django 5.1 on 2026-05-15 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0028_hausgeld_korrektur_felder'),
        ('objekte', '0018_objekt_auto_pipeline'),
        ('personen', '0012_korrektur_service_v1_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hausgeldsollstellung',
            name='neutralisiert_durch_opos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='buchhaltung.hausgeldsollstellung'),
        ),
        migrations.AlterField(
            model_name='hausgeldsollstellung',
            name='neutralisiert_opos_nr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='buchhaltung.hausgeldsollstellung'),
        ),
        migrations.AddIndex(
            model_name='hausgeldsollstellung',
            index=models.Index(fields=['neutralisiert_durch_opos'], name='idx_hg_ss_neutralisiert'),
        ),
        migrations.AddIndex(
            model_name='hausgeldsollstellung',
            index=models.Index(fields=['sollstellungs_typ'], name='idx_hg_ss_typ'),
        ),
        migrations.AddIndex(
            model_name='hausgeldsollstellung',
            index=models.Index(fields=['korrektur_vorgang_id'], name='idx_hg_ss_korrektur_vorgang'),
        ),
        migrations.AddConstraint(
            model_name='hausgeldsollstellung',
            constraint=models.CheckConstraint(condition=models.Q(('soll_betrag__gte', 0), ('sollstellungs_typ', 'korrektur'), _connector='OR'), name='negative_betrag_nur_korrektur'),
        ),
        migrations.AddConstraint(
            model_name='hausgeldsollstellung',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('korrektur_grund__isnull', False), ('korrektur_vorgang_id__isnull', False), ('sollstellungs_typ', 'korrektur')), models.Q(('sollstellungs_typ', 'korrektur'), _negated=True), _connector='OR'), name='korrektur_grund_consistency'),
        ),
    ]
