# Generated by Django 5.1 on 2026-05-16 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0029_korrektur_service_v1_2'),
        ('objekte', '0018_objekt_auto_pipeline'),
        ('personen', '0012_korrektur_service_v1_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontofficeaufgabe',
            name='aufgabe_typ',
            field=models.CharField(choices=[('kein_sepa_mandat', 'SEPA-Mandat fehlt'), ('keine_iban', 'Keine IBAN hinterlegt'), ('keine_hausgeldhistorie', 'Kein Hausgeldsatz'), ('mandat_typ_frst', 'Erst-Mandat (FRST)'), ('sepa_frist_unterschritten', 'SEPA-Frist unterschritten'), ('dateischreibfehler', 'Dateischreibfehler'), ('eigentuemerwechsel_forderung', 'Eigentümerwechsel: Forderung Neueigentümer')], max_length=40),
        ),
        migrations.CreateModel(
            name='EigentuemerwechselVorgang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wechsel_datum', models.DateField()),
                ('meldedatum', models.DateField()),
                ('status', models.CharField(choices=[('vorschau', 'Vorschau'), ('freigegeben', 'Freigegeben')], default='vorschau', max_length=20)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('freigegeben_am', models.DateTimeField(blank=True, null=True)),
                ('auszahlungsbetrag', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('auszahlungs_iban', models.CharField(blank=True, max_length=34)),
                ('notiz', models.TextField(blank=True, null=True)),
                ('auszahlung_unterdruecken', models.BooleanField(default=False)),
                ('einheit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eigentuemerwechsel_vorgaenge', to='objekte.einheit')),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_eigentuemerwechsel', to=settings.AUTH_USER_MODEL)),
                ('freigegeben_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freigegebene_eigentuemerwechsel', to=settings.AUTH_USER_MODEL)),
                ('neueigentuemer_ev', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eigentuemerwechsel_als_neueigentuemer', to='personen.eigentumsverhaeltnis')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eigentuemerwechsel_vorgaenge', to='objekte.objekt')),
                ('voreigentuemer_ev', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eigentuemerwechsel_als_voreigentuemer', to='personen.eigentumsverhaeltnis')),
            ],
            options={
                'verbose_name': 'Eigentümerwechsel-Vorgang',
                'verbose_name_plural': 'Eigentümerwechsel-Vorgänge',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='WechselKorrekturPaar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode', models.DateField()),
                ('original_ist_betrag_vor_korrektur', models.DecimalField(decimal_places=2, max_digits=14)),
                ('korrektur_sollstellung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wechsel_als_korrektur', to='buchhaltung.hausgeldsollstellung')),
                ('neuanlage_sollstellung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wechsel_als_neuanlage', to='buchhaltung.hausgeldsollstellung')),
                ('original_sollstellung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wechsel_als_original', to='buchhaltung.hausgeldsollstellung')),
                ('wechsel_vorgang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='korrektur_paare', to='buchhaltung.eigentuemerwechselvorgang')),
            ],
            options={
                'verbose_name': 'Wechsel-Korrektur-Paar',
                'verbose_name_plural': 'Wechsel-Korrektur-Paare',
                'ordering': ['periode'],
            },
        ),
        migrations.AddConstraint(
            model_name='eigentuemerwechselvorgang',
            constraint=models.CheckConstraint(condition=models.Q(('freigegeben_von_id__isnull', True), models.Q(('freigegeben_von_id', models.F('erstellt_von_id')), _negated=True), _connector='OR'), name='ev_vorgang_vier_augen'),
        ),
    ]
