# Generated by Django 5.1 on 2026-05-16 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0030_eigentuemerwechsel_vorgang'),
        ('dokumente', '0001_initial'),
        ('objekte', '0018_objekt_auto_pipeline'),
        ('personen', '0012_korrektur_service_v1_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontofficeaufgabe',
            name='aufgabe_typ',
            field=models.CharField(choices=[('kein_sepa_mandat', 'SEPA-Mandat fehlt'), ('keine_iban', 'Keine IBAN hinterlegt'), ('keine_hausgeldhistorie', 'Kein Hausgeldsatz'), ('mandat_typ_frst', 'Erst-Mandat (FRST)'), ('sepa_frist_unterschritten', 'SEPA-Frist unterschritten'), ('dateischreibfehler', 'Dateischreibfehler'), ('eigentuemerwechsel_forderung', 'Eigentümerwechsel: Forderung Neueigentümer'), ('saldenmitteilung_wirtschaftsplan', 'Wirtschaftsplan: Saldenmitteilung versenden'), ('stundung_laeuft_ab', 'Umlaufbeschluss-Stundung läuft ab')], max_length=40),
        ),
        migrations.CreateModel(
            name='WirtschaftsplanBeschluss',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beschluss_typ', models.CharField(choices=[('wirtschaftsplan', 'wirtschaftsplan'), ('umlaufbeschluss_stundung', 'umlaufbeschluss_stundung'), ('umlaufbeschluss_sonstig', 'umlaufbeschluss_sonstig')], max_length=30)),
                ('beschluss_datum', models.DateField()),
                ('protokoll_position', models.CharField(blank=True, max_length=50, null=True)),
                ('wirtschaftsplan_beginn', models.DateField()),
                ('wirtschaftsplan_ende', models.DateField(blank=True, null=True)),
                ('gesamt_volumen', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notiz', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('erfasst', 'erfasst'), ('gebucht', 'gebucht'), ('storniert', 'storniert')], default='erfasst', max_length=12)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('gebucht_am', models.DateTimeField(blank=True, null=True)),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_wirtschaftsplan_beschluesse', to=settings.AUTH_USER_MODEL)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wirtschaftsplan_beschluesse', to='objekte.objekt')),
                ('protokoll_dokument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wirtschaftsplan_beschluesse', to='dokumente.dokument')),
            ],
            options={
                'verbose_name': 'Wirtschaftsplan-Beschluss',
                'verbose_name_plural': 'Wirtschaftsplan-Beschlüsse',
                'ordering': ['-beschluss_datum'],
            },
        ),
        migrations.CreateModel(
            name='WirtschaftsplanKorrekturPaar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode', models.DateField()),
                ('differenz_betrag', models.DecimalField(decimal_places=2, max_digits=8)),
                ('beschluss', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='korrektur_paare', to='buchhaltung.wirtschaftsplanbeschluss')),
                ('eigentumsverhaeltnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wp_korrektur_paare', to='personen.eigentumsverhaeltnis')),
                ('korrektur_sollstellung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wp_als_korrektur', to='buchhaltung.hausgeldsollstellung')),
                ('neuanlage_sollstellung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wp_als_neuanlage', to='buchhaltung.hausgeldsollstellung')),
                ('original_sollstellung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wp_als_original', to='buchhaltung.hausgeldsollstellung')),
            ],
            options={
                'verbose_name': 'Wirtschaftsplan-Korrektur-Paar',
                'verbose_name_plural': 'Wirtschaftsplan-Korrektur-Paare',
                'ordering': ['beschluss', 'eigentumsverhaeltnis', 'periode'],
            },
        ),
        migrations.CreateModel(
            name='WirtschaftsplanPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=8)),
                ('beschluss', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positionen', to='buchhaltung.wirtschaftsplanbeschluss')),
                ('buchungsart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wirtschaftsplan_positionen', to='buchhaltung.buchungsart')),
                ('eigentumsverhaeltnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wirtschaftsplan_positionen', to='personen.eigentumsverhaeltnis')),
            ],
            options={
                'verbose_name': 'Wirtschaftsplan-Position',
                'verbose_name_plural': 'Wirtschaftsplan-Positionen',
                'ordering': ['beschluss', 'eigentumsverhaeltnis', 'buchungsart'],
                'constraints': [models.UniqueConstraint(fields=('beschluss', 'eigentumsverhaeltnis', 'buchungsart'), name='uniq_wp_position_beschluss_ev_ba')],
            },
        ),
    ]
