# Generated by Django 5.1 on 2026-05-17 19:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0031_wirtschaftsplan_a1'),
        ('konten', '0005_data_migration_wj'),
        ('objekte', '0019_ebanking_phase_a'),
        ('personen', '0013_wirtschaftsplan_a1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='camtimportlog',
            name='notiz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='camtimportlog',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('pending_mahnwesen_spec', 'Ausstehend (Mahnwesen-Spec)'), ('fehler', 'Fehler')], default='ok', max_length=30),
        ),
        migrations.AddField(
            model_name='camtimportlog',
            name='typ',
            field=models.CharField(choices=[('camt053', 'camt.053 (Kontoauszug)'), ('camt054', 'camt.054 (R-Transactions / Rücklastschriften)')], default='camt053', max_length=8),
        ),
        migrations.AddField(
            model_name='kontoumsatz',
            name='end_to_end_id',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='kontoumsatz',
            name='erkannt_eigentumsverhaeltnis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kontoumsaetze_erkannt', to='personen.eigentumsverhaeltnis'),
        ),
        migrations.AddField(
            model_name='kontoumsatz',
            name='erkannt_gegenkonto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kontoumsatz_gegenkonto', to='konten.konto'),
        ),
        migrations.AddField(
            model_name='kontoumsatz',
            name='erkannt_kreditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kontoumsaetze_erkannt', to='personen.person'),
        ),
        migrations.AddField(
            model_name='kontoumsatz',
            name='erkennungs_begruendung',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kontoumsatz',
            name='erkennungs_konfidenz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='kontoumsatz',
            name='erkennungs_quelle',
            field=models.CharField(blank=True, choices=[('e2e_id', 'EndToEndId-Match (Nebenbuch)'), ('iban_ev', 'IBAN-Match auf EigentumsVerhältnis'), ('bank_match_regel', 'BankMatchRegel'), ('iban_kreditor', 'IBAN-Match auf Kreditor'), ('ki', 'KI-Vorschlag'), ('keine', 'Keine Erkennung')], max_length=20),
        ),
        migrations.AddField(
            model_name='kontoumsatz',
            name='notiz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kontoumsatz',
            name='verbucht_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kontoumsatz',
            name='verbucht_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verbuchte_umsaetze', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kontoumsatz',
            name='status',
            field=models.CharField(choices=[('importiert', 'Importiert'), ('erkannt', 'Erkannt (eindeutig, Konfidenz 1.0)'), ('vorschlag', 'Vorschlag (Konfidenz 0.5–<1.0)'), ('unklar', 'Unklar (keine Erkennung)'), ('verbucht', 'Verbucht (Hauptbuch)'), ('storniert', 'Storniert (GoBD)'), ('manuell', 'Manuell zugeordnet (Legacy)'), ('gebucht', 'Gebucht (Legacy)'), ('ignoriert', 'Ignoriert'), ('unbekannt', 'Unbekannt (kein Objekt)')], default='importiert', max_length=12),
        ),
        migrations.CreateModel(
            name='BankMatchRegel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kontrahent_iban', models.CharField(max_length=34)),
                ('verwendungszweck_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('veraltet', 'Veraltet')], default='aktiv', max_length=10)),
                ('erstellt_aus', models.CharField(choices=[('bestaetigung', 'Bestätigung'), ('korrektur', 'Korrektur'), ('manuell', 'Manuell')], max_length=15)),
                ('trefferzahl', models.IntegerField(default=0)),
                ('letzte_anwendung', models.DateTimeField(blank=True, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('bankkonto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_regeln', to='objekte.bankkonto')),
                ('eigentumsverhaeltnis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_match_regeln', to='personen.eigentumsverhaeltnis')),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_bank_match_regeln', to=settings.AUTH_USER_MODEL)),
                ('gegenkonto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_match_regeln', to='konten.konto')),
                ('kreditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_match_regeln', to='personen.person')),
            ],
            options={
                'verbose_name': 'Bank-Match-Regel',
                'verbose_name_plural': 'Bank-Match-Regeln',
                'ordering': ['-trefferzahl', '-letzte_anwendung'],
            },
        ),
        migrations.CreateModel(
            name='BankErkennungsLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stufe_erreicht', models.CharField(max_length=3)),
                ('quelle', models.CharField(blank=True, choices=[('e2e_id', 'EndToEndId-Match (Nebenbuch)'), ('iban_ev', 'IBAN-Match auf EigentumsVerhältnis'), ('bank_match_regel', 'BankMatchRegel'), ('iban_kreditor', 'IBAN-Match auf Kreditor'), ('ki', 'KI-Vorschlag'), ('keine', 'Keine Erkennung')], max_length=20)),
                ('konfidenz', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('auto_verbucht', models.BooleanField(default=False)),
                ('details_json', models.JSONField(blank=True, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('gegenkonto_vorschlag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_erkennungs_logs', to='konten.konto')),
                ('kontoumsatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erkennungs_logs', to='buchhaltung.kontoumsatz')),
                ('regel_treffer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erkennungs_logs', to='buchhaltung.bankmatchregel')),
            ],
            options={
                'verbose_name': 'Bank-Erkennungs-Log',
                'verbose_name_plural': 'Bank-Erkennungs-Logs',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.AddField(
            model_name='kontoumsatz',
            name='match_regel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='angewendete_umsaetze', to='buchhaltung.bankmatchregel'),
        ),
        migrations.AddIndex(
            model_name='kontoumsatz',
            index=models.Index(fields=['bankkonto', 'status'], name='idx_ku_bankkonto_status'),
        ),
        migrations.AddIndex(
            model_name='kontoumsatz',
            index=models.Index(fields=['status', 'buchungsdatum'], name='idx_ku_status_datum'),
        ),
        migrations.AddConstraint(
            model_name='bankmatchregel',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'aktiv')), fields=('bankkonto', 'kontrahent_iban', 'verwendungszweck_hash'), name='unique_aktive_bankregel'),
        ),
    ]
