# Generated by Django 5.1 on 2026-05-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0017_buchung_wirtschaftsjahr_nr'),
        ('buchhaltung', '0033_ebanking_backfill'),
    ]

    operations = [
    ]
