# Generated by Django 5.1 on 2026-05-19 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung_wp', '0001_initial'),
        ('buchhaltung', '0033_ebanking_backfill'),
        ('objekte', '0019_ebanking_phase_a'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hausgeldsollstellung',
            name='nachhol_aus_wp_beschluss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nachhol_sollstellungen', to='abrechnung_wp.wirtschaftsplan'),
        ),
        migrations.CreateModel(
            name='Auszahlungslauf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[('abrechnungsguthaben', 'Abrechnungsguthaben'), ('ruecklage_entnahme', 'Rücklagen-Entnahme'), ('wp_gutschrift', 'WP-Gutschrift')], max_length=25)),
                ('bezeichnung', models.CharField(blank=True, max_length=255)),
                ('faelligkeitsdatum', models.DateField()),
                ('status', models.CharField(choices=[('erstellt', 'Erstellt'), ('freigegeben', 'Freigegeben'), ('exportiert', 'Exportiert (XML heruntergeladen)'), ('eingereicht', 'Eingereicht')], default='erstellt', max_length=20)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('anzahl_positionen', models.IntegerField(default=0)),
                ('gesamt_summe', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('positionen', models.JSONField(blank=True, default=list)),
                ('datei_pfad', models.CharField(blank=True, max_length=500, null=True)),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auszahlungslaeufe', to=settings.AUTH_USER_MODEL)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auszahlungslaeufe', to='objekte.objekt')),
                ('wirtschaftsplan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auszahlungslaeufe', to='abrechnung_wp.wirtschaftsplan')),
            ],
            options={
                'verbose_name': 'Auszahlungslauf',
                'verbose_name_plural': 'Auszahlungsläufe',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
