# Generated by Django 5.1 on 2026-05-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0034_merge_20260525_0049'),
        ('objekte', '0021_alter_objekt_auto_pipeline_aktiv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchungsart',
            name='bankkonto_typ',
            field=models.CharField(blank=True, choices=[('bewirtschaftung', 'Bewirtschaftungskonto'), ('ruecklage_nach_index', 'Rücklage nach Konto-Index'), ('frei', 'Frei konfigurierbar')], help_text='Routing-Hinweis für den Lastschriftlauf.', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='buchungsart',
            name='buchungstyp',
            field=models.CharField(blank=True, choices=[('sachkonto', 'Sachkontenbuchung'), ('personenkonto', 'Personenkontobuchung'), ('kreditor', 'Kreditorenbuchung')], help_text='Buchungstyp für den Dialogbuchhaltung-Filter. Leer = nicht in der Dialogbuchhaltung wählbar.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='buchungsart',
            name='erloeskonto_default_nr',
            field=models.CharField(blank=True, help_text='Kontonummer des Erlöskontos (z.B. 41900). Wird beim Sollstellungslauf aufgelöst.', max_length=10, verbose_name='Standard-Erlöskonto (Kontonummer)'),
        ),
        migrations.AlterField(
            model_name='buchungsart',
            name='tilgungs_prioritaet',
            field=models.IntegerField(blank=True, help_text='Kleinere Zahl = höhere Priorität. NULL = keine Tilgungs-Priorisierung.', null=True),
        ),
    ]
