# Generated by Django 5.1 on 2026-05-24 23:10

from django.db import migrations


class Migration(migrations.Migration):
    # wirtschaftsjahr_id existiert bereits in der DB — kein SQL nötig
    dependencies = [
        ('buchhaltung', '0035_alter_buchung_wirtschaftsjahr_and_more'),
        ('objekte', '0021_alter_objekt_auto_pipeline_aktiv_and_more'),
    ]

    operations = []
