# Generated by Django 5.1 on 2026-05-24 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0036_alter_buchung_wirtschaftsjahr'),
        ('objekte', '0021_alter_objekt_auto_pipeline_aktiv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hausgeldsollstellungslauf',
            name='wirtschaftsjahr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hausgeld_laeufe', to='objekte.wirtschaftsjahr'),
        ),
        # AlterField buchung.wirtschaftsjahr: Spalte existiert bereits in DB — kein SQL nötig
    ]
