# Generated by Django 5.1 on 2026-05-25 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0037_hgsollstellungslauf_add_wirtschaftsjahr'),
        ('objekte', '0021_alter_objekt_auto_pipeline_aktiv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hausgeldsollstellung',
            name='mahnkarenz_bis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hausgeldsollstellung',
            name='nachhol_aus_wp_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        # AlterField buchung.wirtschaftsjahr already applied in DB — no-op via SeparateDatabaseAndState
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='buchung',
                    name='wirtschaftsjahr',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buchungen_wj', to='objekte.wirtschaftsjahr'),
                ),
            ],
            database_operations=[],
        ),
    ]
