# Generated by Django 5.1 on 2026-05-25 18:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0038_sollstellung_wp_felder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SepaZahlungslauf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('faelligkeitsdatum', models.DateField()),
                ('anzahl_rechnungen', models.IntegerField(default=0)),
                ('summe', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('dateiname', models.CharField(blank=True, default='', max_length=255)),
                ('positionen', models.JSONField(blank=True, default=list)),
                ('buchungs_fehler', models.JSONField(blank=True, default=list)),
                ('uebersprungen', models.JSONField(blank=True, default=list)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sepa_zahlungslaeufe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SEPA-Zahlungslauf',
                'verbose_name_plural': 'SEPA-Zahlungsläufe',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
