# Generated by Django 5.1 on 2026-05-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0039_sepa_zahlungslauf_protokoll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiederkehrendebuchungvorlage',
            name='status',
            field=models.CharField(choices=[('entwurf', 'Entwurf'), ('eingereicht', 'Eingereicht (wartet auf Freigabe)'), ('aktiv', 'Aktiv'), ('pausiert', 'Pausiert'), ('beendet', 'Beendet')], default='entwurf', max_length=12),
        ),
    ]
