# Generated by Django 5.1 on 2026-05-25 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0040_wkz_vorlage_status_eingereicht'),
        ('objekte', '0021_alter_objekt_auto_pipeline_aktiv_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hausgeldsollstellungslauf',
            name='unique_commited_lauf_pro_periode_quelle',
        ),
        migrations.AddConstraint(
            model_name='hausgeldsollstellungslauf',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'commited')), fields=('objekt', 'periode'), name='unique_commited_lauf_pro_objekt_periode'),
        ),
    ]
