# Generated by Django 5.1 on 2026-05-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0042_wkz_vorlage_rechnung_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchungsart',
            name='richtung',
            field=models.CharField(blank=True, choices=[('eingang', 'Eingang (Bank → Personenkonto)'), ('abgang', 'Abgang (Personenkonto → Bank)')], help_text='Nur für Personenkontobuchungen: bestimmt Buchungsrichtung automatisch.', max_length=10, null=True),
        ),
    ]
