# Generated by Django 5.1 on 2026-07-18 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0044_hga_jahresabrechnung_umbau'),
        ('objekte', '0021_alter_objekt_auto_pipeline_aktiv_and_more'),
        ('personen', '0019_person_emails_telefonnummern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hausgeldsollstellung',
            name='negative_betrag_nur_korrektur',
        ),
        migrations.AddConstraint(
            model_name='hausgeldsollstellung',
            constraint=models.CheckConstraint(condition=models.Q(('soll_betrag__gte', 0), ('sollstellungs_typ__in', ['korrektur', 'abrechnungsergebnis']), _connector='OR'), name='negative_betrag_nur_korrektur'),
        ),
    ]
