# Generated by Django 5.1 on 2026-07-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0045_hga_negative_abrechnungsergebnis'),
    ]

    operations = [
        migrations.AddField(
            model_name='einzelabrechnung',
            name='ruecklagen_zufuehrung_gesamt',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Σ der Rücklagen-Zuführung (Sollstellungssplits BA 91x) im WJ.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='einzelabrechnung',
            name='abrechnungsergebnis',
            field=models.DecimalField(decimal_places=2, help_text='(kostenanteil_gesamt + ruecklagen_zufuehrung_gesamt) - hausgeld_soll_gesamt; >0 Nachzahlung, <0 Guthaben.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='einzelabrechnung',
            name='kostenanteil_gesamt',
            field=models.DecimalField(decimal_places=2, help_text='Bewirtschaftungskosten (umlagefähig + nicht umlagefähig).', max_digits=14),
        ),
    ]
