# Generated by Django 5.1 on 2026-07-22 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0046_einzelabrechnung_ruecklagen_zufuehrung_gesamt_and_more'),
        ('objekte', '0021_alter_objekt_auto_pipeline_aktiv_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WirtschaftsplanRuecklage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ba_nr', models.CharField(help_text='Rücklagen-Buchungsart, z. B. 911.', max_length=3)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=12)),
                ('erfasst_am', models.DateTimeField(auto_now=True)),
                ('erfasst_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wirtschaftsjahr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruecklagen_planwerte', to='objekte.wirtschaftsjahr')),
            ],
            options={
                'verbose_name': 'Wirtschaftsplan-Rücklagenzuführung',
                'verbose_name_plural': 'Wirtschaftsplan-Rücklagenzuführungen',
                'constraints': [models.UniqueConstraint(fields=('wirtschaftsjahr', 'ba_nr'), name='uniq_wp_ruecklage_je_wj_ba')],
            },
        ),
    ]
