# Generated by Django 5.1 on 2026-08-31 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0051_wkz_zahlweg'),
        ('objekte', '0022_objekt_handwerker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kreditorop',
            name='vortrag_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kreditorop',
            name='vortrag_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kreditor_op_vortraege', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kreditorop',
            name='vortrag_wj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vorgetragene_kreditor_ops', to='objekte.wirtschaftsjahr', verbose_name='Vorgetragen nach Wirtschaftsjahr'),
        ),
    ]
