# Generated by Django 5.1 on 2026-08-31 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0054_alter_buchungsart_richtung'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kreditorop',
            name='ausgebucht_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kreditorop',
            name='ausgebucht_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kreditor_op_ausbuchungen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kreditorop',
            name='status',
            field=models.CharField(choices=[('offen', 'Offen'), ('bezahlt', 'Bezahlt'), ('teilbezahlt', 'Teilbezahlt'), ('storniert', 'Storniert'), ('ausgebucht', 'Ausgebucht')], default='offen', max_length=20),
        ),
    ]
