# Generated by Django 5.2.12 on 2026-09-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0056_buchungsart_ausbuchung_opos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importordnereinstellung',
            name='bereich',
            field=models.CharField(choices=[('rechnungen', 'Rechnungen'), ('dokumente', 'Dokumente'), ('mails', 'Mails (Posteingang)')], max_length=50, unique=True),
        ),
    ]
