# Generated by Django 5.1 on 2026-09-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0057_alter_importordnereinstellung_bereich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontofficeaufgabe',
            name='aufgabe_typ',
            field=models.CharField(choices=[('kein_sepa_mandat', 'SEPA-Mandat fehlt'), ('keine_iban', 'Keine IBAN hinterlegt'), ('keine_hausgeldhistorie', 'Kein Hausgeldsatz'), ('mandat_typ_frst', 'Erst-Mandat (FRST)'), ('sepa_frist_unterschritten', 'SEPA-Frist unterschritten'), ('dateischreibfehler', 'Dateischreibfehler'), ('eigentuemerwechsel_forderung', 'Eigentümerwechsel: Forderung Neueigentümer'), ('saldenmitteilung_wirtschaftsplan', 'Wirtschaftsplan: Saldenmitteilung versenden'), ('stundung_laeuft_ab', 'Umlaufbeschluss-Stundung läuft ab'), ('schreiben_zur_pruefung', 'Schreiben zur Prüfung'), ('schreiben_nicht_erzeugbar', 'Schreiben nicht erzeugbar')], max_length=40),
        ),
    ]
