# Generated by Django 5.1 on 2026-09-30 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0058_alter_frontofficeaufgabe_aufgabe_typ'),
        ('objekte', '0023_objekt_mailversand_aktiv'),
    ]

    operations = [
        migrations.CreateModel(
            name='MahnEinstellung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahngebuehr', models.DecimalField(decimal_places=2, max_digits=8)),
                ('anzahl_mahnstufen', models.PositiveSmallIntegerField(default=2)),
                ('zinsen_erheben', models.BooleanField(default=False)),
                ('objekt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mahn_einstellung', to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Mahn-Einstellung',
                'verbose_name_plural': 'Mahn-Einstellungen',
                'constraints': [models.CheckConstraint(condition=models.Q(('anzahl_mahnstufen__gte', 1), ('anzahl_mahnstufen__lte', 2)), name='mahneinstellung_anzahl_stufen_1_bis_2')],
            },
        ),
    ]
