# Generated by Django 5.2.12 on 2026-04-03 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buchhaltung', '0001_initial'),
        ('konten', '0001_initial'),
        ('objekte', '0001_initial'),
        ('personen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rechnung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rechnungsnummer', models.CharField(blank=True, max_length=100)),
                ('betrag_netto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('betrag_brutto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mwst_satz', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('rechnungsdatum', models.DateField()),
                ('faelligkeitsdatum', models.DateField()),
                ('leistungsbeschreibung', models.TextField(blank=True)),
                ('pdf_upload', models.FileField(blank=True, upload_to='rechnungen/')),
                ('ki_extraktion', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('erfasst', 'Erfasst'), ('auto_freigabe', 'Auto-Freigabe'), ('in_pruefung', 'In Prüfung'), ('freigegeben', 'Freigegeben'), ('gebucht', 'Gebucht'), ('bezahlt', 'Bezahlt'), ('abgelehnt', 'Abgelehnt')], default='erfasst', max_length=20)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('buchung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechnung', to='buchhaltung.buchung')),
                ('erfasst_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erfasste_rechnungen', to=settings.AUTH_USER_MODEL)),
                ('kostenstelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rechnungen', to='konten.konto')),
                ('lieferant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rechnungen_als_lieferant', to='personen.person')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rechnungen', to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
                'ordering': ['-rechnungsdatum', '-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='Freigabe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rolle', models.CharField(max_length=50)),
                ('entscheidung', models.CharField(choices=[('freigegeben', 'Freigegeben'), ('abgelehnt', 'Abgelehnt')], max_length=20)),
                ('begruendung', models.TextField(blank=True)),
                ('zeitstempel', models.DateTimeField(auto_now_add=True)),
                ('bearbeiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freigaben', to=settings.AUTH_USER_MODEL)),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freigaben', to='rechnungen.rechnung')),
            ],
            options={
                'verbose_name': 'Freigabe',
                'verbose_name_plural': 'Freigaben',
                'ordering': ['-zeitstempel'],
            },
        ),
    ]
