# Generated by Django 5.2.12 on 2026-04-19 23:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekte', '0011_remove_vs101'),
        ('personen', '0005_person_anrede'),
        ('rechnungen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kreditor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_normalisiert', models.CharField(blank=True, max_length=255)),
                ('iban', models.CharField(blank=True, max_length=34, null=True, unique=True)),
                ('strasse', models.CharField(blank=True, max_length=255)),
                ('plz', models.CharField(blank=True, max_length=10)),
                ('ort', models.CharField(blank=True, max_length=100)),
                ('telefon', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('aktiv', models.BooleanField(default=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kreditor',
                'verbose_name_plural': 'Kreditoren',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='rechnung',
            options={'ordering': ['-erstellt_am'], 'verbose_name': 'Rechnung', 'verbose_name_plural': 'Rechnungen'},
        ),
        migrations.AddField(
            model_name='rechnung',
            name='dateiname',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='duplikat_typ',
            field=models.CharField(blank=True, choices=[('hash', 'Exaktes Duplikat (Hash)'), ('rechnungsnummer', 'Gleiche Rechnungsnummer'), ('iban_betrag_datum', 'IBAN + Betrag + Datum'), ('unscharf', 'Unscharfe Übereinstimmung'), ('ocr_unvollstaendig', 'OCR unvollständig')], max_length=30),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='duplikat_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplikate', to='rechnungen.rechnung'),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='lieferant_iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='lieferant_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='lieferant_normalisiert',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='pfad',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='rechnungsnummer_normalisiert',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='sha256_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='textauszug',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='verarbeitungsnotiz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='waehrung',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='betrag_brutto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='betrag_netto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='erfasst_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erfasste_rechnungen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='faelligkeitsdatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='lieferant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rechnungen_als_lieferant', to='personen.person'),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='mwst_satz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='objekt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rechnungen', to='objekte.objekt'),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='rechnungsdatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='status',
            field=models.CharField(choices=[('importiert', 'Importiert'), ('duplikat', 'Duplikat'), ('prueffall', 'Prüffall'), ('erfasst', 'Erfasst'), ('in_pruefung', 'In Prüfung'), ('freigegeben', 'Freigegeben'), ('gebucht', 'Gebucht'), ('bezahlt', 'Bezahlt'), ('abgelehnt', 'Abgelehnt'), ('fehler', 'Fehler')], default='importiert', max_length=20),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='kreditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechnungen', to='rechnungen.kreditor'),
        ),
        migrations.CreateModel(
            name='Verarbeitungslog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aktion', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('details', models.TextField(blank=True)),
                ('zeitpunkt', models.DateTimeField(auto_now_add=True)),
                ('rechnung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rechnungen.rechnung')),
            ],
            options={
                'verbose_name': 'Verarbeitungslog',
                'verbose_name_plural': 'Verarbeitungslogs',
                'ordering': ['-zeitpunkt'],
            },
        ),
    ]
