# Generated by Django 5.1 on 2026-04-24 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0003_abrechnungsart'),
        ('objekte', '0011_remove_vs101'),
        ('rechnungen', '0002_kreditor_alter_rechnung_options_rechnung_dateiname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechnung',
            name='kundennummer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='vorgeschlagenes_konto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vorschlaege', to='konten.konto'),
        ),
        migrations.CreateModel(
            name='KreditorRegel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kundennummer', models.CharField(blank=True, max_length=50)),
                ('treffer', models.IntegerField(default=1)),
                ('zuletzt_angewendet', models.DateTimeField(auto_now=True)),
                ('konto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kreditor_regeln', to='konten.konto')),
                ('kreditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regeln', to='rechnungen.kreditor')),
                ('objekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Kreditor-Regel',
                'verbose_name_plural': 'Kreditor-Regeln',
                'unique_together': {('kreditor', 'kundennummer')},
            },
        ),
    ]
