# Generated by Django 5.2.12 on 2026-05-02 09:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konten', '0003_abrechnungsart'),
        ('objekte', '0014_datenmigration_betreuer'),
        ('rechnungen', '0004_freigabelimitdefault'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rechnung',
            name='buchungskonto',
            field=models.ForeignKey(blank=True, help_text='Pflicht ab Status erkannt; muss zum selben Objekt gehören', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechnungen_buchungskonto', to='konten.konto'),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='erkennungs_konfidenz',
            field=models.JSONField(blank=True, help_text='{"kreditor": 0.95, "objekt": 0.80, "konto": 0.0}', null=True),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='erkennungs_stufe',
            field=models.IntegerField(blank=True, choices=[(1, 'Stufe 1 — Erkannt'), (2, 'Stufe 2 — Prüffall'), (3, 'Stufe 3 — Nicht erkannt')], null=True),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='leistungstext',
            field=models.TextField(blank=True, help_text='Normierter Leistungstext aus OCR/XRechnung'),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='leistungstext_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='zugewiesen_an',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zugewiesene_rechnungen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='freigabelimitdefault',
            name='grenzen',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='freigabelimitdefault',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='status',
            field=models.CharField(choices=[('importiert', 'Importiert'), ('duplikat', 'Duplikat'), ('prueffall', 'Prüffall (alt)'), ('erfasst', 'Erfasst'), ('erkannt', 'Erkannt (Stufe 1)'), ('pruefung_match', 'Prüffall (Stufe 2)'), ('nicht_erkannt', 'Nicht erkannt (Stufe 3)'), ('in_pruefung', 'In Prüfung'), ('freigegeben', 'Freigegeben'), ('gebucht', 'Gebucht'), ('bezahlt', 'Bezahlt'), ('abgelehnt', 'Abgelehnt'), ('fehler', 'Fehler')], default='importiert', max_length=20),
        ),
        migrations.CreateModel(
            name='RechnungsMatchRegel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leistungstext_hash', models.CharField(max_length=64)),
                ('leistungstext_sample', models.TextField(blank=True, help_text='Original-Leistungstext der ersten Bestätigung')),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('veraltet', 'Veraltet')], default='aktiv', max_length=10)),
                ('trefferzahl', models.PositiveIntegerField(default=1)),
                ('erstellt_aus', models.CharField(choices=[('pruefung', 'Prüffall-Identifikation'), ('freigabe_korrektur', 'Freigabe-Korrektur'), ('manuell', 'Manuelle Erfassung')], max_length=25)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('letzte_anwendung', models.DateTimeField(blank=True, null=True)),
                ('buchungskonto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_regeln', to='konten.konto')),
                ('erstellt_durch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_match_regeln', to=settings.AUTH_USER_MODEL)),
                ('kreditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_regeln', to='rechnungen.kreditor')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_regeln', to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Rechnungs-Match-Regel',
                'verbose_name_plural': 'Rechnungs-Match-Regeln',
                'ordering': ['-trefferzahl', '-letzte_anwendung'],
            },
        ),
        migrations.CreateModel(
            name='RechnungsErkennungsLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zeitpunkt', models.DateTimeField(auto_now_add=True)),
                ('stufe', models.IntegerField(blank=True, choices=[(1, 'Stufe 1 — Erkannt'), (2, 'Stufe 2 — Prüffall'), (3, 'Stufe 3 — Nicht erkannt')], null=True)),
                ('dimensionen', models.JSONField(default=dict, help_text='{"kreditor": {match_typ, kandidat_id, konfidenz}, "objekt": {...}, "konto": {...}}')),
                ('ki_aufruf', models.BooleanField(default=False)),
                ('ki_kosten_token', models.PositiveIntegerField(default=0)),
                ('ergebnis_status', models.CharField(blank=True, max_length=20)),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erkennungs_logs', to='rechnungen.rechnung')),
                ('regel_treffer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_eintraege', to='rechnungen.rechnungsmatchregel')),
            ],
            options={
                'verbose_name': 'Erkennungs-Log',
                'verbose_name_plural': 'Erkennungs-Logs',
                'ordering': ['-zeitpunkt'],
            },
        ),
        migrations.AddField(
            model_name='rechnung',
            name='match_regel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='angewendet_auf', to='rechnungen.rechnungsmatchregel'),
        ),
        migrations.AddConstraint(
            model_name='rechnungsmatchregel',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'aktiv')), fields=('kreditor', 'objekt', 'leistungstext_hash'), name='unique_aktive_matchregel'),
        ),
    ]
