# Generated by Django 5.1 on 2026-05-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechnungen', '0005_erkennung_stufen'),
    ]

    operations = [
        migrations.AddField(
            model_name='kreditor',
            name='bic',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
