# Generated by Django 5.2.12 on 2026-05-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechnungen', '0010_v13_aufwandskonto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechnung',
            name='erkennungs_stufe',
            field=models.CharField(blank=True, choices=[('1', 'Stufe 1 — Erkannt'), ('2', 'Stufe 2 — Prüffall (Objektbetreuer)'), ('3', 'Stufe 3 — Nicht erkannt (Frontoffice)')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='routing_ziel',
            field=models.CharField(blank=True, choices=[('limit_workflow', 'Limit-Workflow'), ('objektbetreuer', 'Objektbetreuer'), ('frontoffice', 'Frontoffice-Inbox')], help_text='Ergebnis Phase B: limit_workflow | objektbetreuer | frontoffice', max_length=20),
        ),
        migrations.AlterField(
            model_name='rechnungserkennungslog',
            name='stufe',
            field=models.CharField(blank=True, choices=[('1', 'Stufe 1 — Erkannt'), ('2', 'Stufe 2 — Prüffall (Objektbetreuer)'), ('3', 'Stufe 3 — Nicht erkannt (Frontoffice)')], max_length=3, null=True),
        ),
    ]
