# Generated by Django 5.1 on 2026-05-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechnungen', '0011_alter_rechnung_erkennungs_stufe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechnung',
            name='sepa_lastschrift',
            field=models.BooleanField(default=False, help_text='Zahlung erfolgt per SEPA-Lastschrift (Abbuchung durch Kreditor)'),
        ),
    ]
