# Generated by Django 5.1 on 2026-05-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rechnungen', '0011_wkz_models'),
        ('rechnungen', '0012_rechnung_sepa_lastschrift'),
    ]

    operations = [
    ]
