# Generated by Django 5.1 on 2026-07-14 07:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekte', '0021_alter_objekt_auto_pipeline_aktiv_and_more'),
        ('rechnungen', '0015_rechnung_split_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechnung',
            name='betrag_haushaltsnah',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='§35a EStG Lohn-/Arbeitskostenanteil. Muss <= betrag_brutto sein.', max_digits=12),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='erkennung_ampel',
            field=models.CharField(blank=True, choices=[('gruen', 'Grün'), ('gelb', 'Gelb'), ('rot', 'Rot')], help_text='Gecachtes Ampel-Ergebnis (gruen/gelb/rot) für Liste/Inbox.', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='erkennung_details',
            field=models.JSONField(blank=True, default=dict, help_text='Anzeige-Snapshot je Feld: {feld: {wert, llm_konfidenz, validierung, hinweis, ampel}}. Reine Darstellungsdaten.'),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='erkennung_gesamt_konfidenz',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0–100. Gesamtwert der Verifikations-Ampel (Spec Kap. 5.2).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='ist_schlussrechnung',
            field=models.BooleanField(default=False, help_text='Kennzeichen Schlussrechnung (informativ, Spec B4).'),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='kostenverursacher',
            field=models.ForeignKey(blank=True, help_text='Genau eine Einheit der Liegenschaft der Rechnung (optional). Debitornummer des Eigentümers fließt in den Buchungstext.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verursachte_rechnungen', to='objekte.einheit'),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='skonto_betrag',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Absoluter Skontobetrag; falls nur Prozent genannt aus brutto berechnet.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='skonto_faellig_bis',
            field=models.DateField(blank=True, help_text='Letzter Tag der Skontofrist.', null=True),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='skonto_genutzt',
            field=models.BooleanField(default=False, help_text='Wird beim Zahlungslauf gesetzt, wenn Skonto gezogen wurde.'),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='skonto_prozent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='z.B. 2.00 — aus Rechnung.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='status',
            field=models.CharField(choices=[('importiert', 'Importiert'), ('duplikat', 'Duplikat'), ('prueffall', 'Prüffall (alt)'), ('erfasst', 'Erfasst'), ('erkannt', 'Erkannt (Stufe 1)'), ('pruefung_match', 'Prüffall (Stufe 2)'), ('nicht_erkannt', 'Nicht erkannt (Stufe 3)'), ('in_pruefung', 'In Prüfung'), ('freigegeben', 'Freigegeben'), ('gebucht', 'Gebucht'), ('bezahlt', 'Bezahlt'), ('abgelehnt', 'Abgelehnt'), ('fehler', 'Fehler'), ('in_freigabe', 'In Freigabe'), ('teilbezahlt', 'Teilbezahlt'), ('storniert', 'Storniert')], default='importiert', max_length=20),
        ),
    ]
