# Generated by Django 5.1 on 2026-07-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechnungen', '0016_rechnung_betrag_haushaltsnah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechnung',
            name='status',
            field=models.CharField(choices=[('importiert', 'Importiert'), ('duplikat', 'Duplikat'), ('prueffall', 'Prüffall (alt)'), ('erfasst', 'Erfasst'), ('erkannt', 'Erkannt (Stufe 1)'), ('pruefung_match', 'Prüffall (Stufe 2)'), ('nicht_erkannt', 'Nicht erkannt (Stufe 3)'), ('in_pruefung', 'In Prüfung'), ('freigegeben', 'Freigegeben'), ('gebucht', 'Gebucht'), ('bezahlt', 'Bezahlt'), ('abgelehnt', 'Abgelehnt'), ('fehler', 'Fehler'), ('in_buchhaltung', 'In Buchhaltung (Stufe 1)'), ('zur_freigabe', 'Zur Freigabe (Stufe 2)'), ('in_freigabe', 'In Freigabe (v1.0, migriert)'), ('teilbezahlt', 'Teilbezahlt'), ('storniert', 'Storniert')], default='importiert', max_length=20),
        ),
    ]
