# Generated by Django 5.1 on 2026-07-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechnungen', '0018_in_freigabe_zu_zur_freigabe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechnung',
            name='status',
            field=models.CharField(choices=[('importiert', 'Importiert'), ('duplikat', 'Duplikat'), ('prueffall', 'Prüffall (alt)'), ('erfasst', 'Erfasst'), ('erkannt', 'Erkannt (Stufe 1)'), ('pruefung_match', 'Prüffall (Stufe 2)'), ('nicht_erkannt', 'Nicht erkannt (Stufe 3)'), ('in_pruefung', 'In Prüfung'), ('in_buchhaltung', 'In Buchhaltung (Stufe 1)'), ('zur_freigabe', 'Zur Freigabe (Stufe 2)'), ('freigegeben', 'Freigegeben (OP gebucht)'), ('teilbezahlt', 'Teilbezahlt'), ('bezahlt', 'Bezahlt'), ('abgelehnt', 'Abgelehnt'), ('storniert', 'Storniert'), ('fehler', 'Fehler')], default='importiert', max_length=20),
        ),
    ]
