# Generated by Django 5.1 on 2026-08-03 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumente', '0003_dokument_abgelegt_am_dokument_beleg_nummer_and_more'),
        ('rechnungen', '0020_gebucht_zu_freigegeben'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechnung',
            name='beleg_dokument',
            field=models.OneToOneField(blank=True, help_text='Physischer Beleg (PDF) im DMS — einzige Dateiablage (GoBD)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rechnung', to='dokumente.dokument'),
        ),
    ]
