# Generated by Django 5.1 on 2026-08-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rechnungen', '0021_rechnung_beleg_dokument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rechnung',
            name='pdf_upload',
        ),
    ]
