# Generated by Django 5.1 on 2026-08-17 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handwerker', '0001_initial'),
        ('rechnungen', '0023_rechnung_status_wkz_beleg'),
    ]

    operations = [
        migrations.AddField(
            model_name='kreditor',
            name='gewerk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kreditoren', to='handwerker.gewerk'),
        ),
        migrations.AddField(
            model_name='kreditor',
            name='ist_handwerker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kreditor',
            name='kontakt_person',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='handwerkerauftrag',
            field=models.ForeignKey(blank=True, help_text='n:1 — ein Auftrag kann mehrere Rechnungen haben (Abschlag/Schluss/Gutschrift), eine Rechnung höchstens einen Auftrag.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rechnungen', to='handwerker.handwerkerauftrag'),
        ),
    ]
