# Generated by Django 5.1 on 2026-08-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handwerker', '0002_seed_gewerk'),
        ('rechnungen', '0024_kreditor_gewerk_kreditor_ist_handwerker_and_more'),
    ]

    operations = [
        # Additiv zuerst: neues M2M-Feld anlegen, bevor das alte FK-Feld
        # entfernt wird (siehe Orchestrator-Vorgabe — Datenverlust ist
        # ausgeschlossen: 0 von 62 aktiven Kreditoren hatten am 2026-08-18
        # ein gesetztes 'gewerk', trotzdem bewusst diese Reihenfolge).
        migrations.AddField(
            model_name='kreditor',
            name='gewerke',
            field=models.ManyToManyField(blank=True, related_name='kreditoren', to='handwerker.gewerk'),
        ),
        migrations.RemoveField(
            model_name='kreditor',
            name='gewerk',
        ),
    ]
