# Generated by Django 5.1 on 2026-08-30 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechnungen', '0025_kreditor_gewerke_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KreditorBankverbindung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iban', models.CharField(max_length=34, unique=True)),
                ('bic', models.CharField(blank=True, max_length=11)),
                ('bemerkung', models.CharField(blank=True, help_text='z.B. woher die Bankverbindung stammt (Rechnung, Mitteilung)', max_length=200)),
                ('aktiv', models.BooleanField(default=True)),
                ('erfasst_am', models.DateTimeField(auto_now_add=True)),
                ('erfasst_durch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erfasste_bankverbindungen', to=settings.AUTH_USER_MODEL)),
                ('kreditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankverbindungen', to='rechnungen.kreditor')),
            ],
            options={
                'verbose_name': 'Kreditor-Bankverbindung',
                'verbose_name_plural': 'Kreditor-Bankverbindungen',
                'ordering': ['kreditor', '-erfasst_am'],
            },
        ),
        migrations.CreateModel(
            name='KreditorDublettenPruefung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('erkannter_name', models.CharField(max_length=255)),
                ('erkannte_iban', models.CharField(blank=True, max_length=34)),
                ('anlass', models.CharField(choices=[('fuzzy_name', 'Ähnlicher Name'), ('iban_abweichung', 'Bekannter Name, abweichende Bankverbindung'), ('name_abweichung', 'Bekannte Bankverbindung, abweichender Name')], max_length=25)),
                ('kandidaten', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('offen', 'Offen — Prüfung erforderlich'), ('als_neu_angelegt', 'Als neuer Kreditor angelegt'), ('zugeordnet', 'Bestehendem Kreditor zugeordnet'), ('abgelehnt', 'Abgelehnt')], default='offen', max_length=20)),
                ('entschieden_am', models.DateTimeField(blank=True, null=True)),
                ('notiz', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('entschieden_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kreditor_dubletten_entscheidungen', to=settings.AUTH_USER_MODEL)),
                ('ergebnis_kreditor', models.ForeignKey(blank=True, help_text='Der Kreditor, auf den die Entscheidung hinauslief.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dubletten_entscheidungen', to='rechnungen.kreditor')),
                ('rechnung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dubletten_pruefung', to='rechnungen.rechnung')),
            ],
            options={
                'verbose_name': 'Kreditor-Dublettenprüfung',
                'verbose_name_plural': 'Kreditor-Dublettenprüfungen',
                'ordering': ['-erstellt_am'],
                'indexes': [models.Index(fields=['status'], name='rechnungen__status_d5a097_idx')],
            },
        ),
    ]
