# Generated by Django 5.2.12 on 2026-04-03 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objekt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objekt_typ', models.CharField(choices=[('WEG', 'WEG'), ('ZH', 'ZH'), ('SEV', 'SEV')], max_length=10)),
                ('bezeichnung', models.CharField(max_length=255)),
                ('strasse', models.CharField(max_length=255)),
                ('plz', models.CharField(max_length=10)),
                ('ort', models.CharField(max_length=100)),
                ('baujahr', models.IntegerField(blank=True, null=True)),
                ('verwaltung_seit', models.DateField()),
                ('wirtschaftsjahr_start', models.IntegerField(default=1)),
                ('zahlungsfreigabe_grenzen', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('archiviert', 'Archiviert')], default='aktiv', max_length=20)),
                ('umsatzsteuer_pflichtig', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Objekt',
                'verbose_name_plural': 'Objekte',
                'ordering': ['bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='Liegenschaft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bezeichnung', models.CharField(max_length=255)),
                ('strasse', models.CharField(max_length=255)),
                ('plz', models.CharField(max_length=10)),
                ('ort', models.CharField(max_length=100)),
                ('ist_hauptadresse', models.BooleanField(default=False)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liegenschaften', to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Liegenschaft',
                'verbose_name_plural': 'Liegenschaften',
                'ordering': ['bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='Einheit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('einheit_nr', models.CharField(max_length=20)),
                ('einheit_typ', models.CharField(choices=[('Wohnung', 'Wohnung'), ('Gewerbe', 'Gewerbe'), ('Stellplatz', 'Stellplatz'), ('Sonstiges', 'Sonstiges')], max_length=20)),
                ('lage', models.CharField(max_length=255)),
                ('flaeche_qm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('miteigentumsanteil', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('umsatzsteuer_abrechnungsart', models.CharField(blank=True, choices=[('brutto', 'Brutto'), ('netto', 'Netto')], max_length=10, null=True)),
                ('liegenschaft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='einheiten', to='objekte.liegenschaft')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einheiten', to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Einheit',
                'verbose_name_plural': 'Einheiten',
                'ordering': ['einheit_nr'],
            },
        ),
        migrations.CreateModel(
            name='Bankkonto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('konto_typ', models.CharField(choices=[('bewirtschaftung', 'Bewirtschaftung'), ('ruecklage', 'Rücklage')], max_length=20)),
                ('bezeichnung', models.CharField(max_length=255)),
                ('iban', models.CharField(max_length=34)),
                ('bic', models.CharField(blank=True, max_length=11)),
                ('kontoinhaber', models.CharField(max_length=255)),
                ('reihenfolge', models.PositiveIntegerField(default=1)),
                ('aktiv', models.BooleanField(default=True)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankkonten', to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Bankkonto',
                'verbose_name_plural': 'Bankkonten',
                'ordering': ['reihenfolge', 'bezeichnung'],
            },
        ),
    ]
