# Generated by Django 5.2.12 on 2026-04-04 05:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verteilerschluessel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bezeichnung', models.CharField(max_length=100)),
                ('schluessel_typ', models.CharField(choices=[('MEA', 'Miteigentumsanteil'), ('Flaeche', 'Fläche'), ('Kopf', 'Kopf (je Einheit gleich)'), ('Individuell', 'Individuell')], max_length=20)),
                ('einheit', models.CharField(default='', max_length=20)),
                ('reihenfolge', models.PositiveIntegerField(default=1)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verteilerschluessel', to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Verteilerschlüssel',
                'verbose_name_plural': 'Verteilerschlüssel',
                'ordering': ['objekt', 'reihenfolge', 'bezeichnung'],
                'unique_together': {('objekt', 'bezeichnung')},
            },
        ),
        migrations.CreateModel(
            name='VerteilerschluesselWert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wert', models.DecimalField(decimal_places=4, max_digits=12)),
                ('einheit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verteilerschluessel_werte', to='objekte.einheit')),
                ('schluessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='werte', to='objekte.verteilerschluessel')),
            ],
            options={
                'verbose_name': 'Verteilerschlüssel-Wert',
                'verbose_name_plural': 'Verteilerschlüssel-Werte',
                'ordering': ['schluessel', 'einheit__einheit_nr'],
                'unique_together': {('schluessel', 'einheit')},
            },
        ),
    ]
