# Generated by Django 5.2.12 on 2026-04-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekte', '0002_verteilerschluessel_verteilerschluesselwert'),
    ]

    operations = [
        migrations.AddField(
            model_name='liegenschaft',
            name='anschrift_typ',
            field=models.CharField(choices=[('hauptadresse', 'Hauptadresse'), ('nebenadresse', 'Nebenadresse'), ('zufahrt', 'Zufahrt / Nebengebäude'), ('sonstiges', 'Sonstiges')], default='nebenadresse', max_length=20),
        ),
        migrations.AddField(
            model_name='objekt',
            name='objektnummer',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
