# Generated by Django 5.2.12 on 2026-04-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekte', '0003_liegenschaft_anschrift_typ_objekt_objektnummer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liegenschaft',
            name='anschrift_typ',
        ),
        migrations.RemoveField(
            model_name='liegenschaft',
            name='ist_hauptadresse',
        ),
        migrations.AlterField(
            model_name='liegenschaft',
            name='bezeichnung',
            field=models.CharField(help_text='z.B. "Haus A", "Nr. 12b"', max_length=255),
        ),
    ]
