# Generated by Django 5.2.12 on 2026-04-04 05:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekte', '0004_remove_liegenschaft_anschrift_typ_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='einheit',
            name='liegenschaft',
        ),
        migrations.CreateModel(
            name='Eingang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bezeichnung', models.CharField(help_text='z.B. "Haus A", "Nr. 12b"', max_length=255)),
                ('strasse', models.CharField(max_length=255)),
                ('plz', models.CharField(max_length=10)),
                ('ort', models.CharField(max_length=100)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eingaenge', to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Eingang',
                'verbose_name_plural': 'Eingänge',
                'ordering': ['bezeichnung'],
            },
        ),
        migrations.AddField(
            model_name='einheit',
            name='eingang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='einheiten', to='objekte.eingang'),
        ),
        migrations.DeleteModel(
            name='Liegenschaft',
        ),
    ]
