# Generated by Django 5.2.12 on 2026-04-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objekte', '0005_remove_einheit_liegenschaft_eingang_einheit_eingang_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='einheit',
            name='flaeche_qm',
        ),
        migrations.RemoveField(
            model_name='einheit',
            name='miteigentumsanteil',
        ),
    ]
