# Generated by Django 5.2.12 on 2026-04-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekte', '0006_remove_einheit_flaeche_qm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='einheit',
            name='flaechennummer',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
