# Generated by Django 5.2.12 on 2026-04-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekte', '0007_einheit_flaechennummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankkonto',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
    ]
