# Generated by Django 5.2.12 on 2026-04-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekte', '0009_vs_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='einheit',
            options={'ordering': ['flaechennummer'], 'verbose_name': 'Einheit', 'verbose_name_plural': 'Einheiten'},
        ),
        migrations.AlterField(
            model_name='eingang',
            name='bezeichnung',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='verteilerschluessel',
            name='bezeichnung',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='verteilerschluessel',
            name='schluessel_typ',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
