# Generated by Django 5.2.12 on 2026-05-02 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekte', '0012_objekt_glaeubiger_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='objekt',
            name='betreuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='betreute_objekte', to=settings.AUTH_USER_MODEL, verbose_name='Objektbetreuer'),
        ),
        migrations.AddField(
            model_name='objekt',
            name='betreuer_vertretung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vertretene_objekte', to=settings.AUTH_USER_MODEL, verbose_name='Betreuer-Vertretung'),
        ),
    ]
