# Generated by Django 5.2.12 on 2026-05-07 07:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekte', '0014_datenmigration_betreuer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wirtschaftsjahr',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jahr', models.IntegerField()),
                ('beginn_monat', models.IntegerField()),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('abgeschlossen', 'Abgeschlossen')], default='offen', max_length=20)),
                ('eroeffnet_am', models.DateTimeField(auto_now_add=True)),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True)),
                ('eroeffnet_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eroeffnete_wirtschaftsjahre', to=settings.AUTH_USER_MODEL)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wirtschaftsjahre', to='objekte.objekt')),
                ('vorjahr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folgejahre', to='objekte.wirtschaftsjahr')),
            ],
            options={
                'verbose_name': 'Wirtschaftsjahr',
                'verbose_name_plural': 'Wirtschaftsjahre',
                'ordering': ['objekt', 'jahr'],
            },
        ),
        migrations.CreateModel(
            name='EinheitVerbrauch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vs_code', models.CharField(choices=[('140', '140'), ('141', '141'), ('142', '142'), ('143', '143'), ('144', '144'), ('145', '145')], max_length=3)),
                ('wert', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('einheit_text', models.CharField(blank=True, max_length=20)),
                ('quelle', models.CharField(blank=True, choices=[('manuell', 'Manuell'), ('heiwako_import', 'HEIWAKO-Import')], max_length=20, null=True)),
                ('einheit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verbraeuche', to='objekte.einheit')),
                ('wirtschaftsjahr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einheit_verbraeuche', to='objekte.wirtschaftsjahr')),
            ],
            options={
                'verbose_name': 'Einheit-Verbrauch',
                'verbose_name_plural': 'Einheit-Verbräuche',
            },
        ),
        migrations.AddConstraint(
            model_name='wirtschaftsjahr',
            constraint=models.UniqueConstraint(fields=('objekt', 'jahr'), name='unique_objekt_wirtschaftsjahr'),
        ),
        migrations.AddConstraint(
            model_name='wirtschaftsjahr',
            constraint=models.CheckConstraint(condition=models.Q(('jahr__gte', 2000)), name='wirtschaftsjahr_min_2000'),
        ),
        migrations.AddConstraint(
            model_name='einheitverbrauch',
            constraint=models.UniqueConstraint(fields=('wirtschaftsjahr', 'einheit', 'vs_code'), name='unique_einheit_verbrauch'),
        ),
        migrations.AddConstraint(
            model_name='einheitverbrauch',
            constraint=models.CheckConstraint(condition=models.Q(('vs_code__in', ['140', '141', '142', '143', '144', '145'])), name='einheit_verbrauch_valid_vs_code'),
        ),
    ]
