# Generated by Django 5.1 on 2026-05-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekte', '0018_objekt_auto_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='objekt',
            name='auto_verbuchen_aktiv',
            field=models.BooleanField(default=True, help_text='Eindeutig erkannte Bankbuchungen (Konfidenz 1.0) automatisch ins Hauptbuch übernehmen.', verbose_name='Auto-Verbuchen aktiv (E-Banking)'),
        ),
    ]
