# Generated by Django 5.1 on 2026-05-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objekte', '0017_bankkonto_zahlungsverkehr'),
        ('objekte', '0019_ebanking_phase_a'),
    ]

    operations = [
    ]
