# Generated by Django 5.1 on 2026-05-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekte', '0020_merge_20260525_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objekt',
            name='auto_pipeline_aktiv',
            field=models.BooleanField(default=True, help_text='Deaktivieren um dieses Objekt aus der monatlichen Auto-Pipeline auszuschließen.', verbose_name='Auto-Pipeline aktiv'),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='auto_verbuchen_aktiv',
            field=models.BooleanField(default=True, help_text='Eindeutig erkannte Bankbuchungen (Konfidenz 1.0) automatisch ins Hauptbuch übernehmen.', verbose_name='Auto-Verbuchen aktiv (E-Banking)'),
        ),
    ]
