# Generated by Django 5.1 on 2026-08-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handwerker', '0001_initial'),
        ('objekte', '0021_alter_objekt_auto_pipeline_aktiv_and_more'),
        ('rechnungen', '0024_kreditor_gewerk_kreditor_ist_handwerker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objekt',
            name='handwerker',
            field=models.ManyToManyField(blank=True, related_name='objekte', through='handwerker.ObjektHandwerker', to='rechnungen.kreditor', verbose_name='Zugeordnete Handwerker'),
        ),
    ]
