# Generated by Django 5.1 on 2026-09-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekte', '0022_objekt_handwerker'),
    ]

    operations = [
        migrations.AddField(
            model_name='objekt',
            name='mailversand_aktiv',
            field=models.BooleanField(default=False, help_text='Erst aktivieren, wenn das Objekt live geht. Solange deaktiviert, werden für dieses Objekt KEINE Handwerker-Auftragsmails und EV-Einladungen versendet (schrittweiser Rollout).', verbose_name='E-Mail-Versand aktiv'),
        ),
    ]
