# Generated by Django 5.1 on 2026-08-28 05:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mitarbeiter', '0006_remove_mitarbeiter_freigabe_limit'),
        ('personen', '0019_person_emails_telefonnummern'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalZugang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aktiv', models.BooleanField(default=True, help_text='Die Verwaltung kann den Zugang jederzeit sperren, ohne ihn zu löschen.')),
                ('eingeladen_am', models.DateTimeField(default=django.utils.timezone.now)),
                ('erstaktivierung_am', models.DateTimeField(blank=True, help_text='Null, solange die Einladung nicht angenommen wurde.', null=True)),
                ('letzter_login', models.DateTimeField(blank=True, null=True)),
                ('email_pending', models.EmailField(blank=True, default='', help_text='Neue Adresse, solange sie noch nicht bestätigt ist (Spec Kap. 5.3). Bis zur Bestätigung bleibt die alte Adresse für den Login gültig.', max_length=254, verbose_name='Ausstehende E-Mail-Änderung')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('eingeladen_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_einladungen', to='mitarbeiter.mitarbeiter', verbose_name='Eingeladen von')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_zugang', to='personen.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Portal-Zugang',
                'verbose_name_plural': 'Portal-Zugänge',
                'ordering': ['-eingeladen_am'],
            },
        ),
        migrations.CreateModel(
            name='PortalSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, db_index=True, max_length=100, unique=True)),
                ('gueltig_bis', models.DateTimeField()),
                ('letzter_zugriff', models.DateTimeField(default=django.utils.timezone.now)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('zugang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='portal.portalzugang')),
            ],
            options={
                'verbose_name': 'Portal-Sitzung',
                'verbose_name_plural': 'Portal-Sitzungen',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='PersonStammdatenAenderung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feld', models.CharField(help_text='Feldname, z.B. adresse, telefon, email, iban, bic', max_length=50)),
                ('alter_wert', models.TextField(blank=True, default='')),
                ('neuer_wert', models.TextField(blank=True, default='')),
                ('quelle', models.CharField(default='Portal-Selbständerung', max_length=50)),
                ('zeitstempel', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stammdaten_aenderungen', to='personen.person')),
            ],
            options={
                'verbose_name': 'Stammdaten-Änderung',
                'verbose_name_plural': 'Stammdaten-Änderungen',
                'ordering': ['-zeitstempel'],
                'indexes': [models.Index(fields=['person', 'feld'], name='portal_pers_person__0778cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortalToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[('einladung', 'Einladung'), ('magic', 'Magic Link'), ('email_bestaetigung', 'E-Mail-Bestätigung')], max_length=30)),
                ('token', models.CharField(blank=True, db_index=True, max_length=100, unique=True)),
                ('ziel_email', models.EmailField(blank=True, default='', help_text='Nur bei typ=email_bestaetigung: die zu bestätigende neue Adresse. Wird hier festgehalten, damit ein später geändertes email_pending einen bereits versendeten Link nicht umlenken kann.', max_length=254)),
                ('gueltig_bis', models.DateTimeField()),
                ('verbraucht_am', models.DateTimeField(blank=True, help_text='Einmalverwendung — gesetzt beim Einlösen.', null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('zugang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='portal.portalzugang')),
            ],
            options={
                'verbose_name': 'Portal-Token',
                'verbose_name_plural': 'Portal-Token',
                'ordering': ['-erstellt_am'],
                'indexes': [models.Index(fields=['zugang', 'typ'], name='portal_port_zugang__b7d7da_idx')],
            },
        ),
    ]
