# Generated by Django 5.1 on 2026-08-19 21:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dokumente', '0009_entferne_verknuepfung_typ'),
        ('objekte', '0022_objekt_handwerker'),
        ('personen', '0019_person_emails_telefonnummern'),
        ('vorgaenge', '0005_vorgangereignis_intern_alter_vorgangereignis_typ'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeschlussNummerZaehler',
            fields=[
                ('objekt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='beschluss_zaehler', serialize=False, to='objekte.objekt')),
                ('letzter_zaehler', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Beschluss-Nummern-Zähler',
                'verbose_name_plural': 'Beschluss-Nummern-Zähler',
            },
        ),
        migrations.CreateModel(
            name='Eigentuemerversammlung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arbeitsname', models.CharField(blank=True, default='', help_text='Interne Bezeichnung, z.B. "EV 2026 ordentlich".', max_length=200, verbose_name='Arbeitsname')),
                ('art', models.CharField(choices=[('ordentlich', 'Ordentliche Versammlung'), ('ausserordentl', 'Außerordentliche Versammlung'), ('wiederholung', 'Wiederholungsversammlung')], default='ordentlich', max_length=15)),
                ('termin', models.DateTimeField(blank=True, null=True)),
                ('ort', models.CharField(blank=True, default='', max_length=255)),
                ('raum_buchung_notizen', models.TextField(blank=True, default='')),
                ('terminvorschlaege', models.JSONField(blank=True, default=list, help_text='Vorschlagsliste aus der Beiratsabstimmung: [{"termin": "2026-03-15T19:00", "notiz": "..."}]', verbose_name='Terminvorschläge')),
                ('stimmprinzip', models.CharField(choices=[('kopf', 'Kopfprinzip (§ 25 Abs. 2 WEG: eine Stimme je Eigentümer)'), ('objekt', 'Objektprinzip (eine Stimme je Einheit)'), ('mea', 'Wertprinzip (Stimme nach MEA)')], default='kopf', help_text='Gesetzlicher Regelfall ist das Kopfprinzip; abweichende Regelungen stehen in der Teilungserklärung.', max_length=10)),
                ('mea_wirtschaftsjahr', models.IntegerField(default=0, help_text='Wirtschaftsjahr für den MEA-Verteilerschlüssel; 0 = zeitlos (Regelfall, siehe VerteilerschluesselWert.wirtschaftsjahr).', verbose_name='MEA-Wirtschaftsjahr')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('in_bearbeitung', 'In Bearbeitung'), ('einladungen_versendet', 'Einladungen versendet'), ('durchgefuehrt', 'Durchgeführt'), ('beschluesse_verarbeitet', 'Beschlüsse verarbeitet'), ('archiviert', 'Archiviert')], default='entwurf', max_length=25)),
                ('task1_terminierung_erledigt', models.BooleanField(default=False)),
                ('task2_tagesordnung_erledigt', models.BooleanField(default=False)),
                ('task3_einladung_erledigt', models.BooleanField(default=False)),
                ('task4_durchfuehrung_erledigt', models.BooleanField(default=False)),
                ('task5_beschlussfassung_erledigt', models.BooleanField(default=False)),
                ('einladungstext', models.TextField(blank=True, default='', help_text='Editierbarer Einladungstext (Vorlage wird beim Anlegen gesetzt).')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('einladung_versendet_am', models.DateTimeField(blank=True, null=True)),
                ('durchgefuehrt_am', models.DateTimeField(blank=True, null=True)),
                ('versammlungsleiter', models.CharField(blank=True, default='', max_length=200)),
                ('protokollfuehrer', models.CharField(blank=True, default='', max_length=200)),
                ('einladungs_pdf', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ev_einladung', to='dokumente.dokument')),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_eigentuemerversammlungen', to=settings.AUTH_USER_MODEL)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eigentuemerversammlungen', to='objekte.objekt')),
                ('protokoll_pdf', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ev_protokoll', to='dokumente.dokument')),
            ],
            options={
                'verbose_name': 'Eigentümerversammlung',
                'verbose_name_plural': 'Eigentümerversammlungen',
                'ordering': ['-termin', '-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='EVTeilnehmer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zusage_status', models.CharField(choices=[('offen', 'Keine Rückmeldung'), ('zugesagt', 'Zusage'), ('abgesagt', 'Absage')], default='offen', max_length=10)),
                ('zusage_am', models.DateTimeField(blank=True, null=True)),
                ('zusage_quelle', models.CharField(blank=True, choices=[('portal', 'Portal'), ('manuell', 'Manuell erfasst')], default='', help_text='Wer die Rückmeldung erfasst hat.', max_length=10)),
                ('ist_anwesend', models.BooleanField(blank=True, help_text='NULL = noch nicht erfasst. (Django-5-Ersatz für das in Django 4.0 entfernte NullBooleanField.)', null=True, verbose_name='Anwesend')),
                ('anwesenheit_erfasst_am', models.DateTimeField(blank=True, null=True)),
                ('vertreter_name', models.CharField(blank=True, default='', help_text='Freitext, wenn der Bevollmächtigte kein Person-Datensatz ist.', max_length=200)),
                ('stimmkraft', models.DecimalField(decimal_places=4, default=0, help_text='Snapshot, ermittelt nach Eigentuemerversammlung.stimmprinzip (siehe services/stimmkraft_service.py). 0 = nicht mehr stimmberechtigt, z.B. nach Eigentümerwechsel — die Zeile bleibt als Ladungsnachweis erhalten.', max_digits=12)),
                ('ev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teilnehmer', to='versammlung.eigentuemerversammlung')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ev_teilnahmen', to='personen.person')),
                ('vertreten_durch', models.ForeignKey(blank=True, help_text='Bevollmächtigter aus dem Personenstamm. Die Stimmkraft bleibt bei diesem Teilnehmer und wird dem Vertreter nicht zusätzlich angerechnet.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ev_vertretungen', to='personen.person')),
                ('vollmacht_dokument', models.ForeignKey(blank=True, help_text='Vollmachtnachweis — erster Prüfpunkt bei Anfechtung.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ev_vollmachten', to='dokumente.dokument')),
            ],
            options={
                'verbose_name': 'EV-Teilnehmer',
                'verbose_name_plural': 'EV-Teilnehmer',
                'ordering': ['ev', 'person__nachname', 'person__vorname'],
            },
        ),
        migrations.CreateModel(
            name='EVTeilnehmerAnteil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('einheit_nr_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('mea_wert_snapshot', models.DecimalField(blank=True, decimal_places=4, help_text='MEA aus Verteilerschluessel(vs_typ="mea") zum Snapshot-Zeitpunkt.', max_digits=12, null=True, verbose_name='MEA (Snapshot)')),
                ('eigentumsverhaeltnis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ev_teilnehmer_anteile', to='personen.eigentumsverhaeltnis')),
                ('teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anteile', to='versammlung.evteilnehmer')),
            ],
            options={
                'verbose_name': 'EV-Teilnehmer-Anteil',
                'verbose_name_plural': 'EV-Teilnehmer-Anteile',
                'ordering': ['teilnehmer', 'einheit_nr_snapshot'],
            },
        ),
        migrations.CreateModel(
            name='EVVersandprotokoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kanal', models.CharField(choices=[('portal', 'Portal (Dokument + Benachrichtigungsmail)'), ('email', 'E-Mail mit PDF-Anhang'), ('epost', 'EPost (manueller Postversand)')], max_length=10)),
                ('status', models.CharField(choices=[('erfolgreich', 'Erfolgreich'), ('fehlgeschlagen', 'Fehlgeschlagen'), ('uebersprungen', 'Übersprungen')], default='erfolgreich', max_length=15)),
                ('empfaenger', models.CharField(blank=True, default='', help_text='Verwendete E-Mail-Adresse bzw. Postanschrift (Nachweis).', max_length=255, verbose_name='Empfänger')),
                ('epost_pfad', models.CharField(blank=True, default='', help_text='Docker-Pfad der abgelegten PDF (unter MEDIA_ROOT/epost/…), nie ein Host- oder Windows-Pfad.', max_length=500)),
                ('fehlertext', models.TextField(blank=True, default='')),
                ('versendet_am', models.DateTimeField(auto_now_add=True)),
                ('ev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versandprotokolle', to='versammlung.eigentuemerversammlung')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ev_versandprotokolle', to='personen.person')),
                ('versendet_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ev_versandprotokolle', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EV-Versandprotokoll',
                'verbose_name_plural': 'EV-Versandprotokolle',
                'ordering': ['ev', 'person__nachname', '-versendet_am'],
            },
        ),
        migrations.CreateModel(
            name='Tagesordnungspunkt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nummer', models.IntegerField(help_text='Fortlaufend ab 1.')),
                ('titel', models.CharField(max_length=255)),
                ('erlaeuterung', models.TextField(blank=True, default='', help_text='Optionale Hintergrundinformation zum TOP.', verbose_name='Erläuterung')),
                ('beschlussvorlage', models.TextField(blank=True, default='', help_text='Wortlaut, über den abgestimmt wird. Pflicht außer bei abstimmungsmodus="kein_beschluss".')),
                ('abstimmungsmodus', models.CharField(choices=[('einfache_mehrheit', 'Einfache Mehrheit (Ja > Nein)'), ('qualifizierte_mehrheit', 'Qualifizierte Mehrheit (Schwelle laut TE)'), ('einstimmigkeit', 'Einstimmigkeit (alle abgegebenen Stimmen)'), ('allstimmigkeit', 'Allstimmigkeit (alle Eigentümer)'), ('kein_beschluss', 'Ohne Beschluss (Bericht/Information)')], default='einfache_mehrheit', max_length=25)),
                ('mehrheit_schwelle', models.DecimalField(blank=True, decimal_places=2, help_text='Nur bei abstimmungsmodus="qualifizierte_mehrheit": erforderlicher Ja-Anteil an den abgegebenen Stimmen (z.B. 66.67). Grundlage ist die Teilungserklärung — die frühere "doppelt qualifizierte Mehrheit" ist mit der WEG-Reform 2020 entfallen.', max_digits=5, null=True, verbose_name='Mehrheitsschwelle in Prozent')),
                ('abstimmung_ja', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('abstimmung_nein', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('abstimmung_enthaltung', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('abstimmungsergebnis', models.CharField(choices=[('offen', 'Noch nicht abgestimmt'), ('angenommen', 'Angenommen'), ('abgelehnt', 'Abgelehnt'), ('vertagt', 'Vertagt'), ('entfallen', 'Entfallen')], default='offen', max_length=12)),
                ('ergebnis_bemerkung', models.TextField(blank=True, default='')),
                ('triggert_vorgang', models.BooleanField(default=False, help_text='Erzeugt bei Annahme einen Vorgang (z.B. Sanierung). Ein Handwerkerauftrag entsteht daraus manuell — auftrag_service.erstelle_auftrag verlangt einen Kreditor.', verbose_name='Folge-Vorgang anlegen')),
                ('triggert_wirtschaftsplan', models.BooleanField(default=False, help_text='Erzeugt bei Annahme eine Aufgabe zur Erfassung über buchhaltung.wirtschaftsplan_beschluss_service.', verbose_name='Wirtschaftsplan-Beschluss vormerken')),
                ('ev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagesordnung', to='versammlung.eigentuemerversammlung')),
            ],
            options={
                'verbose_name': 'Tagesordnungspunkt',
                'verbose_name_plural': 'Tagesordnungspunkte',
                'ordering': ['ev', 'nummer'],
            },
        ),
        migrations.CreateModel(
            name='EVStimme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('votum', models.CharField(choices=[('ja', 'Ja'), ('nein', 'Nein'), ('enthaltung', 'Enthaltung')], max_length=10)),
                ('stimmkraft', models.DecimalField(decimal_places=4, max_digits=12)),
                ('erfasst_am', models.DateTimeField(auto_now_add=True)),
                ('erfasst_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erfasste_ev_stimmen', to=settings.AUTH_USER_MODEL)),
                ('teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stimmen', to='versammlung.evteilnehmer')),
                ('top', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stimmen', to='versammlung.tagesordnungspunkt')),
            ],
            options={
                'verbose_name': 'EV-Einzelstimme',
                'verbose_name_plural': 'EV-Einzelstimmen',
                'ordering': ['top', 'teilnehmer'],
            },
        ),
        migrations.CreateModel(
            name='EVEreignis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[('erstellt', 'EV erstellt'), ('task_erledigt', 'Task als erledigt markiert'), ('task_zurueckgesetzt', 'Task zurückgesetzt'), ('statuswechsel', 'Statuswechsel'), ('termin_geaendert', 'Termin/Ort geändert'), ('top_angelegt', 'TOP angelegt'), ('top_geaendert', 'TOP geändert'), ('top_geloescht', 'TOP gelöscht'), ('einladung_erzeugt', 'Einladungs-PDF erzeugt'), ('einladung_versendet', 'Einladung versendet'), ('versand_fehler', 'Versandfehler'), ('zusage_erfasst', 'Zusage/Absage erfasst'), ('stimmkraft_ermittelt', 'Stimmkraft ermittelt'), ('anwesenheit_erfasst', 'Anwesenheit erfasst'), ('abstimmung_erfasst', 'Abstimmung erfasst'), ('abstimmung_korrigiert', 'Abstimmung korrigiert'), ('beschluss_erzeugt', 'Beschluss in Sammlung aufgenommen'), ('vorgang_erzeugt', 'Folge-Vorgang erzeugt'), ('wp_aufgabe_erzeugt', 'Wirtschaftsplan-Aufgabe erzeugt'), ('protokoll_erzeugt', 'Protokoll-PDF erzeugt'), ('kommentar', 'Kommentar')], max_length=25)),
                ('text', models.TextField(blank=True, default='')),
                ('alter_wert', models.CharField(blank=True, default='', max_length=200)),
                ('neuer_wert', models.CharField(blank=True, default='', max_length=200)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('erstellt_von', models.ForeignKey(blank=True, help_text='NULL = systemgeneriert (Celery-Task).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_ev_ereignisse', to=settings.AUTH_USER_MODEL)),
                ('ev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ereignisse', to='versammlung.eigentuemerversammlung')),
                ('top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ereignisse', to='versammlung.tagesordnungspunkt')),
            ],
            options={
                'verbose_name': 'EV-Ereignis',
                'verbose_name_plural': 'EV-Ereignisse',
                'ordering': ['erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='Beschluss',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nummer', models.IntegerField(editable=False, help_text='Fortlaufende Nummer je Objekt, Vergabe über BeschlussNummerZaehler.')),
                ('beschluss_datum', models.DateField()),
                ('ort', models.CharField(blank=True, default='', max_length=255)),
                ('wortlaut', models.TextField(help_text='Wortlaut des Beschlusses — unveränderlich (§ 24 Abs. 7 WEG).')),
                ('ergebnis_ja', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('ergebnis_nein', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('ergebnis_enthaltung', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('anfechtung_status', models.CharField(choices=[('keine', 'Keine Anfechtung bekannt'), ('anhaengig', 'Anfechtungsklage anhängig'), ('abgewiesen', 'Klage abgewiesen'), ('aufgehoben', 'Beschluss gerichtlich aufgehoben')], default='keine', max_length=12)),
                ('anfechtung_notiz', models.TextField(blank=True, default='')),
                ('aufgehoben_am', models.DateField(blank=True, null=True)),
                ('gerichtlicher_hinweis', models.TextField(blank=True, default='')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('dokument', models.ForeignKey(blank=True, help_text='DMS-Dokument mit dokument_typ="beschluss".', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beschluesse', to='dokumente.dokument')),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_beschluesse', to=settings.AUTH_USER_MODEL)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beschluesse', to='objekte.objekt')),
                ('vorgang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ev_beschluesse', to='vorgaenge.vorgang')),
                ('ev', models.ForeignKey(blank=True, help_text='NULL bei Umlaufbeschluss (§ 23 Abs. 3 WEG) — vorgesehen, Erfassungsweg folgt in einer späteren Phase.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beschluesse', to='versammlung.eigentuemerversammlung')),
                ('top', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beschluss', to='versammlung.tagesordnungspunkt')),
            ],
            options={
                'verbose_name': 'Beschluss',
                'verbose_name_plural': 'Beschluss-Sammlung',
                'ordering': ['objekt', '-nummer'],
            },
        ),
        migrations.AddIndex(
            model_name='eigentuemerversammlung',
            index=models.Index(fields=['objekt', '-termin'], name='versammlung_objekt__90ad40_idx'),
        ),
        migrations.AddIndex(
            model_name='eigentuemerversammlung',
            index=models.Index(fields=['status'], name='versammlung_status_f12cff_idx'),
        ),
        migrations.AddConstraint(
            model_name='evteilnehmer',
            constraint=models.UniqueConstraint(fields=('ev', 'person'), name='uniq_teilnehmer_je_ev'),
        ),
        migrations.AddConstraint(
            model_name='evteilnehmeranteil',
            constraint=models.UniqueConstraint(fields=('teilnehmer', 'eigentumsverhaeltnis'), name='uniq_anteil_je_teilnehmer'),
        ),
        migrations.AddIndex(
            model_name='evversandprotokoll',
            index=models.Index(fields=['ev', 'kanal'], name='versammlung_ev_id_709b27_idx'),
        ),
        migrations.AddConstraint(
            model_name='tagesordnungspunkt',
            constraint=models.UniqueConstraint(fields=('ev', 'nummer'), name='uniq_top_nummer_je_ev'),
        ),
        migrations.AddConstraint(
            model_name='evstimme',
            constraint=models.UniqueConstraint(fields=('top', 'teilnehmer'), name='uniq_stimme_je_top'),
        ),
        migrations.AddConstraint(
            model_name='beschluss',
            constraint=models.UniqueConstraint(fields=('objekt', 'nummer'), name='uniq_beschluss_nummer_je_objekt'),
        ),
    ]
