# Generated by Django 5.2.12 on 2026-09-26 13:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekte', '0022_objekt_handwerker'),
        ('versammlung', '0003_stimm_verteilerschluessel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versammlungsort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bezeichnung', models.CharField(max_length=200)),
                ('strasse', models.CharField(blank=True, default='', max_length=255)),
                ('plz', models.CharField(blank=True, default='', max_length=10)),
                ('ort_text', models.CharField(blank=True, default='', max_length=120)),
                ('zusatz', models.CharField(blank=True, default='', help_text='Raum, Etage, Zugangshinweis o.ä.', max_length=255)),
                ('aktiv', models.BooleanField(default=True, help_text='Deaktivieren statt Löschen — PROTECT-Referenzen aus bestehenden Eigentümerversammlungen bleiben erhalten.')),
            ],
            options={
                'verbose_name': 'Versammlungsort',
                'verbose_name_plural': 'Versammlungsorte',
                'ordering': ['bezeichnung'],
            },
        ),
        migrations.AddField(
            model_name='eigentuemerversammlung',
            name='abschluss_erledigt_am',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt des Checkout-Abschlusses (Spec v1.1 Kap. 4C, API-Vertrag 3.7) — Beschlussnummern wurden vergeben, aber der Status wechselt erst mit dem Protokoll-Upload (3.8) auf "beschluesse_verarbeitet". Markiert außerdem, dass protokoll-upload aufgerufen werden darf.', null=True),
        ),
        migrations.AlterField(
            model_name='eigentuemerversammlung',
            name='status',
            field=models.CharField(choices=[('entwurf', 'Entwurf'), ('in_bearbeitung', 'In Bearbeitung'), ('einladungen_versendet', 'Einladungen versendet'), ('ausgecheckt', 'Ausgecheckt (Abstimmtool)'), ('durchgefuehrt', 'Durchgeführt (Altdaten)'), ('beschluesse_verarbeitet', 'Beschlüsse verarbeitet'), ('archiviert', 'Archiviert')], default='entwurf', max_length=25),
        ),
        migrations.AlterField(
            model_name='evereignis',
            name='typ',
            field=models.CharField(choices=[('erstellt', 'EV erstellt'), ('task_erledigt', 'Task als erledigt markiert'), ('task_zurueckgesetzt', 'Task zurückgesetzt'), ('statuswechsel', 'Statuswechsel'), ('termin_geaendert', 'Termin/Ort geändert'), ('top_angelegt', 'TOP angelegt'), ('top_geaendert', 'TOP geändert'), ('top_geloescht', 'TOP gelöscht'), ('einladung_erzeugt', 'Einladungs-PDF erzeugt'), ('einladung_versendet', 'Einladung versendet'), ('versand_fehler', 'Versandfehler'), ('zusage_erfasst', 'Zusage/Absage erfasst'), ('stimmkraft_ermittelt', 'Stimmkraft ermittelt'), ('anwesenheit_erfasst', 'Anwesenheit erfasst'), ('abstimmung_erfasst', 'Abstimmung erfasst'), ('abstimmung_korrigiert', 'Abstimmung korrigiert'), ('beschluss_erzeugt', 'Beschluss in Sammlung aufgenommen'), ('vorgang_erzeugt', 'Folge-Vorgang erzeugt'), ('wp_aufgabe_erzeugt', 'Wirtschaftsplan-Aufgabe erzeugt'), ('protokoll_erzeugt', 'Protokoll-PDF erzeugt'), ('checkout', 'Checkout (Übergabe ans Abstimmtool)'), ('checkout_zurueckgenommen', 'Checkout zurückgenommen'), ('abschluss_erzeugt', 'Abschluss — Beschlussnummern vergeben'), ('protokoll_hochgeladen', 'Protokoll vom Abstimmtool hochgeladen'), ('kommentar', 'Kommentar')], max_length=25),
        ),
        migrations.CreateModel(
            name='EVStimmgrundlage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ist_kopfprinzip', models.BooleanField(default=False, help_text='§ 25 Abs. 2 WEG: eine Stimme je Person, unabhängig von der Anzahl ihrer Einheiten. NICHT zu verwechseln mit Verteilerschluessel.vs_typ="kopf" (Objektprinzip, Anzahl je Einheit) — siehe Klassendokumentation.', verbose_name='Echtes Kopfprinzip')),
                ('wirtschaftsjahr', models.IntegerField(default=0, help_text='Wirtschaftsjahr, aus dem die Werte des Verteilerschlüssels gelesen werden; 0 = zeitlos. Ohne Bedeutung bei ist_kopfprinzip=True.')),
                ('ist_standard', models.BooleanField(default=False, help_text='Vorbelegung für den ersten Tagesordnungspunkt der EV. Höchstens eine Stimmgrundlage je EV darf das sein.')),
                ('bezeichnung_anzeige', models.CharField(help_text='Anzeigetext, z.B. "Kopfprinzip" oder die Bezeichnung des Verteilerschlüssels — wird dem externen Abstimmtool je TOP angezeigt (API-Vertrag v1.1 Abschnitt 3.1).', max_length=120)),
                ('ev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stimmgrundlagen', to='versammlung.eigentuemerversammlung')),
                ('verteilerschluessel', models.ForeignKey(blank=True, help_text='Gesetzt, wenn NICHT das echte Kopfprinzip gilt — Grundlage ist dann dieser Verteilerschlüssel des Objekts. Verbrauchsschlüssel (vs_typ="verbrauch") sind keine zulässige Stimmgrundlage (siehe clean()).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ev_stimmgrundlagen', to='objekte.verteilerschluessel')),
            ],
            options={
                'verbose_name': 'EV-Stimmgrundlage',
                'verbose_name_plural': 'EV-Stimmgrundlagen',
                'ordering': ['ev', 'bezeichnung_anzeige'],
            },
        ),
        migrations.AddField(
            model_name='tagesordnungspunkt',
            name='stimmgrundlage',
            field=models.ForeignKey(blank=True, help_text='Grundlage, mit der bei diesem TOP abgestimmt wird (Spec v1.1 Kap. 3). Muss zur eigenen EV gehören. NULL nur bei Alt-TOPs vor der Datenmigration bzw. bei über die Admin-Oberfläche angelegten Testdaten — der Checkout (checkout_service) verlangt sie für jeden abstimmungspflichtigen TOP und lehnt sonst ab. PROTECT: eine einmal verwendete Stimmgrundlage darf nicht verschwinden, solange ein TOP sie referenziert.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tagesordnungspunkte', to='versammlung.evstimmgrundlage'),
        ),
        migrations.CreateModel(
            name='EVTeilnehmerAnteilWert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wert_snapshot', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('anteil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wert_snapshots', to='versammlung.evteilnehmeranteil')),
                ('stimmgrundlage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anteil_werte', to='versammlung.evstimmgrundlage')),
            ],
            options={
                'verbose_name': 'EV-Teilnehmer-Anteil-Wert',
                'verbose_name_plural': 'EV-Teilnehmer-Anteil-Werte (je Grundlage)',
                'ordering': ['anteil', 'stimmgrundlage'],
            },
        ),
        migrations.CreateModel(
            name='EVTeilnehmerStimmkraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stimmkraft', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('stimmgrundlage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teilnehmer_stimmkraft', to='versammlung.evstimmgrundlage')),
                ('teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stimmkraft_snapshots', to='versammlung.evteilnehmer')),
            ],
            options={
                'verbose_name': 'EV-Teilnehmer-Stimmkraft',
                'verbose_name_plural': 'EV-Teilnehmer-Stimmkraft (je Grundlage)',
                'ordering': ['teilnehmer', 'stimmgrundlage'],
            },
        ),
        migrations.AddField(
            model_name='eigentuemerversammlung',
            name='versammlungsort',
            field=models.ForeignKey(blank=True, help_text='Katalogeintrag zur Vorbelegung von "ort" (Autocomplete). Rein informativ — maßgeblich für Einladung/Protokoll bleibt das Textfeld "ort" (GoBD-Snapshot zum Versammlungszeitpunkt).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eigentuemerversammlungen', to='versammlung.versammlungsort'),
        ),
        migrations.AddConstraint(
            model_name='evstimmgrundlage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ist_kopfprinzip', False), ('verteilerschluessel__isnull', False)), models.Q(('ist_kopfprinzip', True), ('verteilerschluessel__isnull', True)), _connector='OR'), name='evstimmgrundlage_entweder_vs_oder_kopf'),
        ),
        migrations.AddConstraint(
            model_name='evstimmgrundlage',
            constraint=models.UniqueConstraint(condition=models.Q(('ist_standard', True)), fields=('ev',), name='uniq_standard_stimmgrundlage_je_ev'),
        ),
        migrations.AddConstraint(
            model_name='evstimmgrundlage',
            constraint=models.UniqueConstraint(condition=models.Q(('ist_kopfprinzip', True)), fields=('ev',), name='uniq_kopfprinzip_je_ev'),
        ),
        migrations.AddConstraint(
            model_name='evstimmgrundlage',
            constraint=models.UniqueConstraint(fields=('ev', 'verteilerschluessel'), name='uniq_verteilerschluessel_je_ev'),
        ),
        migrations.AddConstraint(
            model_name='evteilnehmeranteilwert',
            constraint=models.UniqueConstraint(fields=('anteil', 'stimmgrundlage'), name='uniq_anteilwert_je_anteil_und_grundlage'),
        ),
        migrations.AddConstraint(
            model_name='evteilnehmerstimmkraft',
            constraint=models.UniqueConstraint(fields=('teilnehmer', 'stimmgrundlage'), name='uniq_stimmkraft_je_teilnehmer_und_grundlage'),
        ),
    ]
