# Generated by Django 5.1 on 2026-10-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versammlung', '0005_stimmgrundlage_datenmigration'),
    ]

    operations = [
        migrations.AddField(
            model_name='beschluss',
            name='ergebnis',
            field=models.CharField(choices=[('angenommen', 'Angenommen'), ('abgelehnt', 'Abgelehnt')], default='angenommen', help_text='Abstimmungsergebnis des Antrags. Auch abgelehnte Anträge (Negativbeschlüsse) kommen in die Sammlung — nach BGH ist auch die Ablehnung ein Beschluss.', max_length=12),
        ),
    ]
