# Generated by Django 5.2.12 on 2026-10-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versammlung', '0007_tagesordnungspunkt_eltern'),
    ]

    operations = [
        migrations.AddField(
            model_name='beschluss',
            name='ueberschrift',
            field=models.CharField(blank=True, default='', help_text='Überschrift des Beschlusses — bei EV-Beschlüssen der TOP-Titel (Snapshot), bei Nachträgen frei erfasst.', max_length=255),
        ),
        migrations.AlterField(
            model_name='beschluss',
            name='wortlaut',
            field=models.TextField(help_text='Wortlaut/Beschlusstext — unveränderlich (§ 24 Abs. 7 WEG).'),
        ),
    ]
