# Generated by Django 5.2.12 on 2026-10-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versammlung', '0008_beschluss_ueberschrift_alter_beschluss_wortlaut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evereignis',
            name='typ',
            field=models.CharField(choices=[('erstellt', 'EV erstellt'), ('task_erledigt', 'Task als erledigt markiert'), ('task_zurueckgesetzt', 'Task zurückgesetzt'), ('statuswechsel', 'Statuswechsel'), ('termin_geaendert', 'Termin/Ort geändert'), ('top_angelegt', 'TOP angelegt'), ('top_geaendert', 'TOP geändert'), ('top_geloescht', 'TOP gelöscht'), ('einladung_erzeugt', 'Einladungs-PDF erzeugt'), ('einladung_versendet', 'Einladung versendet'), ('versand_fehler', 'Versandfehler'), ('zusage_erfasst', 'Zusage/Absage erfasst'), ('stimmkraft_ermittelt', 'Stimmkraft ermittelt'), ('anwesenheit_erfasst', 'Anwesenheit erfasst'), ('abstimmung_erfasst', 'Abstimmung erfasst'), ('abstimmung_korrigiert', 'Abstimmung korrigiert'), ('beschluss_erzeugt', 'Beschluss in Sammlung aufgenommen'), ('vorgang_erzeugt', 'Folge-Vorgang erzeugt'), ('wp_aufgabe_erzeugt', 'Wirtschaftsplan-Aufgabe erzeugt'), ('protokoll_erzeugt', 'Protokoll-PDF erzeugt'), ('checkout', 'Checkout (Übergabe ans Abstimmtool)'), ('checkout_zurueckgenommen', 'Checkout zurückgenommen'), ('abschluss_erzeugt', 'Abschluss — Beschlussnummern vergeben'), ('abschluss_top_ohne_beschluss', 'TOP ohne Beschluss (beim Abschluss übersprungen)'), ('protokoll_hochgeladen', 'Protokoll vom Abstimmtool hochgeladen'), ('kommentar', 'Kommentar')], max_length=32),
        ),
    ]
