# Generated by Django 5.2.12 on 2026-04-03 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objekte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prozess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prozess_typ', models.CharField(choices=[('objekt_anlegen', 'Objekt anlegen'), ('eigentuemerwechsel', 'Eigentümerwechsel'), ('jahresabrechnung', 'Jahresabrechnung'), ('mieterwechsel', 'Mieterwechsel')], max_length=30)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('steps_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('abgeschlossen', 'Abgeschlossen'), ('abgebrochen', 'Abgebrochen')], default='aktiv', max_length=20)),
                ('gestartet_am', models.DateTimeField(auto_now_add=True)),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True)),
                ('gestartet_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestartete_prozesse', to=settings.AUTH_USER_MODEL)),
                ('objekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prozesse', to='objekte.objekt')),
            ],
            options={
                'verbose_name': 'Prozess',
                'verbose_name_plural': 'Prozesse',
                'ordering': ['-gestartet_am'],
            },
        ),
    ]
