# Generated by Django 5.1 on 2026-08-08 11:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objekte', '0021_alter_objekt_auto_pipeline_aktiv_and_more'),
        ('personen', '0019_person_emails_telefonnummern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VorgangNummerZaehler',
            fields=[
                ('jahr', models.IntegerField(primary_key=True, serialize=False)),
                ('letzter_zaehler', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vorgang-Nummer-Zähler',
                'verbose_name_plural': 'Vorgang-Nummer-Zähler',
            },
        ),
        migrations.CreateModel(
            name='Vorgang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nummer', models.CharField(editable=False, max_length=20, unique=True)),
                ('quelle', models.CharField(choices=[('manuell', 'Manuell'), ('mail', 'E-Mail'), ('telefon', 'Telefon'), ('beschluss', 'Beschluss'), ('portal', 'Eigentümer-Portal')], default='manuell', max_length=10)),
                ('betreff', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('in_bearbeitung', 'In Bearbeitung'), ('wartet_extern', 'Wartet auf Dritte'), ('wiedervorlage', 'Wiedervorlage'), ('erledigt', 'Erledigt'), ('storniert', 'Storniert')], default='offen', max_length=20)),
                ('prioritaet', models.CharField(choices=[('niedrig', 'Niedrig'), ('normal', 'Normal'), ('hoch', 'Hoch')], default='normal', max_length=10)),
                ('faellig_am', models.DateField(blank=True, null=True)),
                ('wiedervorlage_am', models.DateField(blank=True, null=True)),
                ('mail_referenz', models.CharField(blank=True, max_length=255, null=True)),
                ('telefon_rufnummer', models.CharField(blank=True, max_length=30, null=True)),
                ('portal_sichtbar', models.BooleanField(default=False)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geschlossen_am', models.DateTimeField(blank=True, null=True)),
                ('einheit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vorgaenge', to='objekte.einheit')),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_vorgaenge', to=settings.AUTH_USER_MODEL)),
                ('geschlossen_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='geschlossene_vorgaenge', to=settings.AUTH_USER_MODEL)),
                ('objekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vorgaenge', to='objekte.objekt')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vorgaenge', to='personen.person')),
                ('zugewiesen_an', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zugewiesene_vorgaenge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vorgang',
                'verbose_name_plural': 'Vorgänge',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='VorgangEreignis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[('kommentar', 'Kommentar'), ('statuswechsel', 'Statuswechsel'), ('zuweisung_geaendert', 'Zuweisung geändert'), ('dokument_verknuepft', 'Dokument verknüpft'), ('system_wiedervorlage_faellig', 'System: Wiedervorlage fällig')], max_length=30)),
                ('text', models.TextField(blank=True, null=True)),
                ('alter_wert', models.CharField(blank=True, max_length=100, null=True)),
                ('neuer_wert', models.CharField(blank=True, max_length=100, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_vorgang_ereignisse', to=settings.AUTH_USER_MODEL)),
                ('vorgang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ereignisse', to='vorgaenge.vorgang')),
            ],
            options={
                'verbose_name': 'Vorgangs-Ereignis',
                'verbose_name_plural': 'Vorgangs-Ereignisse',
                'ordering': ['erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='VorgangTyp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('bezeichnung', models.CharField(max_length=100)),
                ('standard_prioritaet', models.CharField(choices=[('niedrig', 'Niedrig'), ('normal', 'Normal'), ('hoch', 'Hoch')], default='normal', max_length=10)),
                ('aktiv', models.BooleanField(default=True)),
                ('sortierung', models.IntegerField(default=0)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erstellte_vorgang_typen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vorgangs-Typ',
                'verbose_name_plural': 'Vorgangs-Typen',
                'ordering': ['sortierung', 'bezeichnung'],
            },
        ),
        migrations.AddField(
            model_name='vorgang',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vorgaenge', to='vorgaenge.vorgangtyp'),
        ),
    ]
