# Generated by Django 5.1 on 2026-08-16 15:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorgaenge', '0002_seed_vorgangtyp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vorgangtyp',
            name='antwort_vorschlag_aktiv',
            field=models.BooleanField(default=False, help_text='Erzeugt bei Anlage eines Vorgangs dieses Typs automatisch einen KI-Antwortvorschlag (Folgeauftrag KI-Antwortvorschlag).', verbose_name='KI-Antwortvorschlag bei Anlage'),
        ),
        migrations.AlterField(
            model_name='vorgangereignis',
            name='typ',
            field=models.CharField(choices=[('kommentar', 'Kommentar'), ('statuswechsel', 'Statuswechsel'), ('zuweisung_geaendert', 'Zuweisung geändert'), ('dokument_verknuepft', 'Dokument verknüpft'), ('system_wiedervorlage_faellig', 'System: Wiedervorlage fällig'), ('antwort_vorschlag_erzeugt', 'KI-Antwortvorschlag erzeugt'), ('antwort_vorschlag_bearbeitet', 'KI-Antwortvorschlag bearbeitet'), ('antwort_vorschlag_freigegeben', 'KI-Antwortvorschlag freigegeben'), ('antwort_vorschlag_verworfen', 'KI-Antwortvorschlag verworfen')], max_length=30),
        ),
        migrations.CreateModel(
            name='VorgangAntwortVorschlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_ki', models.TextField(blank=True, default='', help_text='Unveränderter KI-Originaltext — wird nie überschrieben (GoBD).', verbose_name='KI-Originaltext')),
                ('text', models.TextField(blank=True, default='', help_text='Aktueller (ggf. vom Mitarbeiter bearbeiteter) Stand.', verbose_name='Aktueller Text')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('freigegeben', 'Freigegeben'), ('verworfen', 'Verworfen'), ('fehlgeschlagen', 'Fehlgeschlagen')], default='entwurf', max_length=20)),
                ('modell', models.CharField(blank=True, default='', max_length=50)),
                ('fehler', models.TextField(blank=True, null=True)),
                ('erzeugt_am', models.DateTimeField(auto_now_add=True)),
                ('bearbeitet_am', models.DateTimeField(blank=True, null=True)),
                ('freigegeben_am', models.DateTimeField(blank=True, null=True)),
                ('bearbeitet_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bearbeitete_antwort_vorschlaege', to=settings.AUTH_USER_MODEL)),
                ('erzeugt_von', models.ForeignKey(blank=True, help_text='None = automatisch bei Vorgangsanlage erzeugt.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erzeugte_antwort_vorschlaege', to=settings.AUTH_USER_MODEL)),
                ('freigegeben_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freigegebene_antwort_vorschlaege', to=settings.AUTH_USER_MODEL)),
                ('vorgang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antwort_vorschlaege', to='vorgaenge.vorgang')),
            ],
            options={
                'verbose_name': 'KI-Antwortvorschlag',
                'verbose_name_plural': 'KI-Antwortvorschläge',
                'ordering': ['-erzeugt_am'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'entwurf')), fields=('vorgang',), name='uniq_ein_entwurf_je_vorgang')],
            },
        ),
    ]
