# Generated by Django 5.1 on 2026-08-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorgaenge', '0004_seed_antwort_vorschlag_aktiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='vorgangereignis',
            name='intern',
            field=models.BooleanField(default=True, help_text='True (Default, sichere Seite) = nur für Mitarbeiter im Verlauf sichtbar. False = für den Eigentümer sichtbar (siehe vorgang_service.portal_ansicht) — muss bei jeder Erzeugung eines Ereignisses bewusst gesetzt werden, ein Versehen bedeutet dadurch immer "zu wenig", nie "zu viel" preisgegeben. Bestandszeilen vor Einführung dieses Felds sind automatisch intern (Migration ohne Datenmigration). Wird ausschließlich bei der Anlage gesetzt — GoBD: kein Endpunkt/keine UI zum nachträglichen Umschalten.', verbose_name='Intern'),
        ),
        migrations.AlterField(
            model_name='vorgangereignis',
            name='typ',
            field=models.CharField(choices=[('kommentar', 'Kommentar'), ('statuswechsel', 'Statuswechsel'), ('zuweisung_geaendert', 'Zuweisung geändert'), ('dokument_verknuepft', 'Dokument verknüpft'), ('system_wiedervorlage_faellig', 'System: Wiedervorlage fällig'), ('antwort_vorschlag_erzeugt', 'KI-Antwortvorschlag erzeugt'), ('antwort_vorschlag_bearbeitet', 'KI-Antwortvorschlag bearbeitet'), ('antwort_vorschlag_freigegeben', 'KI-Antwortvorschlag freigegeben'), ('antwort_vorschlag_verworfen', 'KI-Antwortvorschlag verworfen'), ('handwerker_beauftragt', 'Handwerker beauftragt'), ('handwerker_angenommen', 'Handwerker: Auftrag angenommen'), ('handwerker_abgelehnt', 'Handwerker: Auftrag abgelehnt'), ('handwerker_abgeschlossen', 'Handwerker: Auftrag abgeschlossen'), ('handwerker_abgelaufen', 'Handwerker: Auftragsbestätigung abgelaufen')], max_length=30),
        ),
    ]
