# Generated by Django 5.1 on 2026-09-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorgaenge', '0006_portal_system_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vorgangtyp',
            name='portal_erstellbar',
            field=models.BooleanField(default=False, help_text='Steuert, ob der Typ im Portal-Formular "Neuer Vorgang" zur Auswahl steht (Spec Portal-Erweiterung v1.1, Kap. 4).', verbose_name='Im Portal erstellbar'),
        ),
    ]
