# Generated by Django 5.2.12 on 2026-09-14 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekte', '0022_objekt_handwerker'),
        ('personen', '0021_seed_adress_einzelfelder'),
        ('vorgaenge', '0007_vorgangtyp_portal_erstellbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vorgangereignis',
            name='typ',
            field=models.CharField(choices=[('kommentar', 'Kommentar'), ('statuswechsel', 'Statuswechsel'), ('zuweisung_geaendert', 'Zuweisung geändert'), ('dokument_verknuepft', 'Dokument verknüpft'), ('system_wiedervorlage_faellig', 'System: Wiedervorlage fällig'), ('antwort_vorschlag_erzeugt', 'KI-Antwortvorschlag erzeugt'), ('antwort_vorschlag_bearbeitet', 'KI-Antwortvorschlag bearbeitet'), ('antwort_vorschlag_freigegeben', 'KI-Antwortvorschlag freigegeben'), ('antwort_vorschlag_verworfen', 'KI-Antwortvorschlag verworfen'), ('handwerker_beauftragt', 'Handwerker beauftragt'), ('handwerker_angenommen', 'Handwerker: Auftrag angenommen'), ('handwerker_abgelehnt', 'Handwerker: Auftrag abgelehnt'), ('handwerker_abgeschlossen', 'Handwerker: Auftrag abgeschlossen'), ('handwerker_abgelaufen', 'Handwerker: Auftragsbestätigung abgelaufen'), ('mail_eingegangen', 'E-Mail eingegangen')], max_length=30),
        ),
        migrations.CreateModel(
            name='MailImportProtokoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateiname', models.CharField(max_length=255)),
                ('message_id', models.CharField(blank=True, db_index=True, default='', help_text='Message-ID-Header der Mail — Duplikatkennung.', max_length=255)),
                ('absender', models.CharField(blank=True, default='', max_length=320)),
                ('absender_name', models.CharField(blank=True, default='', max_length=200)),
                ('betreff', models.CharField(blank=True, default='', max_length=500)),
                ('gesendet_am', models.DateTimeField(blank=True, null=True)),
                ('body_auszug', models.TextField(blank=True, default='', help_text='Erste Zeichen des Mailtexts — für die Sichtprüfung im Report.')),
                ('anhaenge_anzahl', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('vorgang_neu', 'Neuer Vorgang angelegt'), ('thread_zuordnung', 'Bestehendem Vorgang zugeordnet'), ('duplikat', 'Duplikat (Message-ID bereits verarbeitet)'), ('nicht_zugeordnet', 'Nicht zugeordnet (Absender unbekannt)'), ('fehler', 'Fehler')], max_length=20)),
                ('zuordnung_quelle', models.CharField(choices=[('email_exakt', 'E-Mail-Adresse exakt'), ('name_betreff', 'Name/Objekt aus Betreff'), ('ki', 'KI-Vorschlag'), ('keine', 'Keine Zuordnung')], default='keine', max_length=20)),
                ('mehrdeutig', models.BooleanField(default=False, help_text='True = die Adresse passt auf mehrere Personen oder die Person besitzt mehrere Einheiten; die Einheit wurde dann bewusst NICHT geraten.')),
                ('ki_typ_code', models.CharField(blank=True, default='', max_length=30)),
                ('ki_prioritaet', models.CharField(blank=True, default='', max_length=10)),
                ('ki_betreff', models.CharField(blank=True, default='', max_length=200)),
                ('ki_konfidenz', models.DecimalField(blank=True, decimal_places=3, help_text='0.000–1.000, Selbsteinschätzung der KI.', max_digits=4, null=True)),
                ('ki_begruendung', models.TextField(blank=True, default='')),
                ('ki_modell', models.CharField(blank=True, default='', max_length=50)),
                ('ki_fehler', models.TextField(blank=True, default='')),
                ('bewertung', models.CharField(choices=[('offen', 'Noch nicht bewertet'), ('richtig', 'Erkennung korrekt'), ('teilweise', 'Teilweise korrekt'), ('falsch', 'Erkennung falsch')], default='offen', max_length=10)),
                ('bewertung_notiz', models.TextField(blank=True, default='')),
                ('fehler', models.TextField(blank=True, default='')),
                ('verarbeitet_am', models.DateTimeField(auto_now_add=True)),
                ('einheit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_import_protokolle', to='objekte.einheit')),
                ('objekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_import_protokolle', to='objekte.objekt')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_import_protokolle', to='personen.person')),
                ('vorgang', models.ForeignKey(blank=True, help_text='Der angelegte bzw. zugeordnete Vorgang (SET_NULL: das Protokoll überlebt das Löschen eines Testvorgangs).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_importe', to='vorgaenge.vorgang')),
            ],
            options={
                'verbose_name': 'Mail-Import-Protokoll',
                'verbose_name_plural': 'Mail-Import-Protokolle',
                'ordering': ['-verarbeitet_am'],
            },
        ),
    ]
