# Generated by Django 5.1 on 2026-09-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorgaenge', '0008_alter_vorgangereignis_typ_mailimportprotokoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailimportprotokoll',
            name='personen_treffer',
            field=models.IntegerField(default=0, help_text='Wie viele Personen die Absenderadresse fuehren. >1 heisst geteilte Adresse — in den Stammdaten sind das teils Ehepaare mit getrennten Datensaetzen, teils echte Dubletten. Macht die Kennzahl "Einheit eindeutig" erklaerbar.', verbose_name='Personen unter dieser Adresse'),
        ),
        migrations.AlterField(
            model_name='mailimportprotokoll',
            name='mehrdeutig',
            field=models.BooleanField(default=False, help_text='True = Person oder Einheit liessen sich nicht eindeutig bestimmen (Adresse von mehreren Personen genutzt, mehrere Einheiten, oder nur ein beendetes Eigentumsverhaeltnis). Was offen blieb, wurde bewusst NICHT geraten.'),
        ),
        migrations.AlterField(
            model_name='mailimportprotokoll',
            name='zuordnung_quelle',
            field=models.CharField(choices=[('email_exakt', 'E-Mail-Adresse exakt'), ('email_geteilt', 'E-Mail-Adresse, von mehreren Personen genutzt'), ('name_betreff', 'Name/Objekt aus Betreff'), ('ki', 'KI-Vorschlag'), ('keine', 'Keine Zuordnung')], default='keine', max_length=20),
        ),
    ]
