# Generated by Django 5.1 on 2026-09-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorgaenge', '0009_mailimportprotokoll_personen_treffer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailimportprotokoll',
            name='bezug_message_id',
            field=models.CharField(blank=True, default='', help_text='Message-ID der Mail, auf die geantwortet wurde. Ohne dieses Feld laesst sich im Nachhinein nicht mehr feststellen, ob eine Thread-Zuordnung mangels Bezug unterblieb oder weil der bezogene Vorgang zum Verarbeitungszeitpunkt noch nicht existierte.', max_length=255, verbose_name='Bezug (In-Reply-To)'),
        ),
    ]
