# Generated by Django 5.1 on 2026-09-14 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorgaenge', '0010_mailimportprotokoll_bezug_message_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailimportprotokoll',
            name='erledigt_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailimportprotokoll',
            name='erledigt_notiz',
            field=models.TextField(blank=True, default='', help_text='Warum so entschieden — vor allem beim Verwerfen die einzige Spur, die bleibt.'),
        ),
        migrations.AddField(
            model_name='mailimportprotokoll',
            name='erledigt_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erledigte_mail_importe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailimportprotokoll',
            name='posteingang_status',
            field=models.CharField(choices=[('automatisch', 'Automatisch zugeordnet'), ('offen', 'Offen — wartet auf Zuordnung'), ('zugeordnet', 'Von Hand zugeordnet'), ('abgelegt', 'Nur abgelegt (kein Vorgang noetig)'), ('verworfen', 'Verworfen')], db_index=True, default='offen', help_text='"automatisch" = beim Import bereits zugeordnet, gehoert nie in die Posteingangsliste. "offen" = wartet auf eine Entscheidung.', max_length=12, verbose_name='Posteingang'),
        ),
    ]
