# Generated by Django 5.1 on 2026-09-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorgaenge', '0013_seed_vorgangtyp_fallakten'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphMailAbruf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktiv', models.BooleanField(default=False, help_text='Erst aktivieren, wenn die Azure-App (Mail.Read) steht und die MS_GRAPH_-Werte in .env.prod eingetragen sind. Solange aus, ruft IMMOCORE keine info@-Mails per Graph ab.', verbose_name='Graph-Mailabruf aktiv')),
                ('letzter_abruf', models.DateTimeField(blank=True, help_text='Ab diesem Zeitpunkt (receivedDateTime, minus kleinem Sicherheitsfenster) wird beim nächsten Lauf weitergeholt. Leer = ab dem ersten Lauf.', null=True, verbose_name='Empfangszeitpunkt der zuletzt geholten Mail')),
                ('zuletzt_gelaufen', models.DateTimeField(blank=True, null=True, verbose_name='Task zuletzt gelaufen')),
                ('letzte_meldung', models.TextField(blank=True, default='', verbose_name='Letzte Meldung')),
            ],
            options={
                'verbose_name': 'Graph-Mailabruf',
                'verbose_name_plural': 'Graph-Mailabruf',
            },
        ),
    ]
