# Generated by Django 5.1 on 2026-09-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vorgaenge', '0014_graphmailabruf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vorgangereignis',
            name='typ',
            field=models.CharField(choices=[('kommentar', 'Kommentar'), ('statuswechsel', 'Statuswechsel'), ('zuweisung_geaendert', 'Zuweisung geändert'), ('dokument_verknuepft', 'Dokument verknüpft'), ('system_wiedervorlage_faellig', 'System: Wiedervorlage fällig'), ('antwort_vorschlag_erzeugt', 'KI-Antwortvorschlag erzeugt'), ('antwort_vorschlag_bearbeitet', 'KI-Antwortvorschlag bearbeitet'), ('antwort_vorschlag_freigegeben', 'KI-Antwortvorschlag freigegeben'), ('antwort_vorschlag_verworfen', 'KI-Antwortvorschlag verworfen'), ('handwerker_beauftragt', 'Handwerker beauftragt'), ('handwerker_angenommen', 'Handwerker: Auftrag angenommen'), ('handwerker_abgelehnt', 'Handwerker: Auftrag abgelehnt'), ('handwerker_abgeschlossen', 'Handwerker: Auftrag abgeschlossen'), ('handwerker_abgelaufen', 'Handwerker: Auftragsbestätigung abgelaufen'), ('mail_eingegangen', 'E-Mail eingegangen'), ('schreiben_erstellt', 'Schreiben erstellt'), ('schreiben_versendet', 'Schreiben versendet')], max_length=30),
        ),
    ]
