# Generated by Django 5.2.12 on 2026-04-03 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objekte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_typ', models.CharField(choices=[('Eigentuemer', 'Eigentümer'), ('Mieter', 'Mieter'), ('Dienstleister', 'Dienstleister'), ('Sonstiges', 'Sonstiges')], max_length=100)),
                ('ist_firma', models.BooleanField(default=False)),
                ('vorname', models.CharField(blank=True, max_length=100)),
                ('nachname', models.CharField(blank=True, max_length=100)),
                ('firmenname', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=50)),
                ('adresse', models.TextField(blank=True)),
                ('ibans', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Personen',
                'ordering': ['nachname', 'vorname', 'firmenname'],
            },
        ),
        migrations.CreateModel(
            name='SEPAMandat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mandatsreferenz', models.CharField(max_length=35, unique=True)),
                ('iban', models.CharField(max_length=34)),
                ('bic', models.CharField(blank=True, max_length=11)),
                ('unterzeichnet_am', models.DateField()),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SEPA-Mandat',
                'verbose_name_plural': 'SEPA-Mandate',
                'ordering': ['-unterzeichnet_am'],
            },
        ),
        migrations.CreateModel(
            name='EigentumsVerhaeltnis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beginn', models.DateField()),
                ('ende', models.DateField(blank=True, null=True)),
                ('einheit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eigentumsverhaeltnisse', to='objekte.einheit')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eigentumsverhaeltnisse', to='personen.person')),
            ],
            options={
                'verbose_name': 'Eigentumsverhältnis',
                'verbose_name_plural': 'Eigentumsverhältnisse',
                'ordering': ['-beginn'],
            },
        ),
        migrations.CreateModel(
            name='HausgeldHistorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gueltig_ab', models.DateField()),
                ('eigentumsverhaeltnis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hausgeld_historie', to='personen.eigentumsverhaeltnis')),
                ('erstellt_von', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hausgeld_historien', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hausgeld-Historie',
                'verbose_name_plural': 'Hausgeld-Historien',
                'ordering': ['-gueltig_ab'],
            },
        ),
        migrations.CreateModel(
            name='Mietvertrag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beginn', models.DateField()),
                ('ende', models.DateField(blank=True, null=True)),
                ('kaltmiete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nebenkosten_vorauszahlung', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('einheit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mietvertraege', to='objekte.einheit')),
                ('mieter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mietvertraege', to='personen.person')),
            ],
            options={
                'verbose_name': 'Mietvertrag',
                'verbose_name_plural': 'Mietverträge',
                'ordering': ['-beginn'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='sepa_mandat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personen', to='personen.sepamandat'),
        ),
    ]
