# Generated by Django 5.2.12 on 2026-05-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personen', '0006_person_vorname2_nachname2'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='briefanrede',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
