# Generated by Django 5.2.12 on 2026-05-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personen', '0007_briefanrede'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='briefanrede2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
