# Generated by Django 5.1 on 2026-05-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personen', '0008_hausgeldhistorie_kontoart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hausgeldhistorie',
            name='quelle',
            field=models.CharField(blank=True, default='import', help_text='Woher kommt dieser Eintrag: wizard, import, beschluss', max_length=20, verbose_name='Quelle'),
        ),
        migrations.AlterField(
            model_name='person',
            name='briefanrede',
            field=models.CharField(blank=True, default='', help_text='z.B. "Sehr geehrte Frau Müller"', max_length=255, verbose_name='Briefanrede'),
        ),
        migrations.AlterField(
            model_name='person',
            name='briefanrede2',
            field=models.CharField(blank=True, default='', help_text='Briefanrede der zweiten Person (bei Eheleuten)', max_length=255, verbose_name='Briefanrede 2. Person'),
        ),
        migrations.AlterField(
            model_name='sepamandat',
            name='sequence_type',
            field=models.CharField(blank=True, default='RCUR', help_text='FRST = Erstlastschrift, RCUR = Folgelastschrift', max_length=4, verbose_name='Sequenztyp'),
        ),
    ]
