# Generated by Django 5.1 on 2026-05-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personen', '0011_sepamandat_sequence_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eigentumsverhaeltnis',
            name='ende',
            field=models.DateField(blank=True, help_text='Null = aktuell aktiv', null=True),
        ),
        migrations.AlterField(
            model_name='hausgeldhistorie',
            name='betrag',
            field=models.DecimalField(decimal_places=2, help_text='Monatliches Soll in EUR. 0,00 ist erlaubt.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='hausgeldhistorie',
            name='gueltig_ab',
            field=models.DateField(help_text='Datum, ab dem dieser Betrag gilt. Typisch der 1. eines Monats.'),
        ),
    ]
