# Generated by Django 5.1 on 2026-05-16 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _migrate_quelle_werte(apps, schema_editor):
    HausgeldHistorie = apps.get_model('personen', 'HausgeldHistorie')
    HausgeldHistorie.objects.filter(quelle='csv_import').update(
        quelle='import',
        import_referenz='csv_import',
    )
    HausgeldHistorie.objects.filter(quelle='wizard').update(
        quelle='import',
        import_referenz='wizard_erstanlage',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('buchhaltung', '0031_wirtschaftsplan_a1'),
        ('konten', '0005_data_migration_wj'),
        ('personen', '0012_korrektur_service_v1_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hausgeldhistorie',
            name='beschluss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hausgeld_historien', to='buchhaltung.wirtschaftsplanbeschluss'),
        ),
        migrations.AddField(
            model_name='hausgeldhistorie',
            name='gueltig_bis',
            field=models.DateField(blank=True, help_text='Letzter Gültigkeitstag. NULL = aktuell gültig.', null=True),
        ),
        migrations.AddField(
            model_name='hausgeldhistorie',
            name='import_referenz',
            field=models.CharField(blank=True, help_text='Pflicht wenn quelle=import. Identifiziert den Import-Lauf.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hausgeldhistorie',
            name='quelle',
            field=models.CharField(choices=[('beschluss', 'Beschluss'), ('import', 'Import (Massenimport / Erstanlage)')], max_length=20),
        ),
        migrations.RunPython(
            _migrate_quelle_werte,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='hausgeldhistorie',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quelle', 'beschluss'), ('beschluss__isnull', False), ('import_referenz__isnull', True)), models.Q(('quelle', 'import'), ('beschluss__isnull', True), ('import_referenz__isnull', False)), _connector='OR'), name='hausgeld_historie_quelle_consistency'),
        ),
    ]
