# Generated by Django 5.1 on 2026-05-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personen', '0009_alter_hausgeldhistorie_quelle_and_more'),
        ('personen', '0013_wirtschaftsplan_a1'),
    ]

    operations = [
    ]
