# Generated by Django 5.1 on 2026-05-19 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung_wp', '0001_initial'),
        ('buchhaltung', '0034_wp_quelle'),
        ('konten', '0005_data_migration_wj'),
        ('personen', '0013_wirtschaftsplan_a1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hausgeldhistorie',
            name='hausgeld_historie_quelle_consistency',
        ),
        migrations.AddField(
            model_name='hausgeldhistorie',
            name='quelle_wp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hausgeld_historien', to='abrechnung_wp.wirtschaftsplan'),
        ),
        migrations.AlterField(
            model_name='hausgeldhistorie',
            name='quelle',
            field=models.CharField(choices=[('beschluss', 'Beschluss'), ('import', 'Import (Massenimport / Erstanlage)'), ('wirtschaftsplan', 'Wirtschaftsplan-Beschluss')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='hausgeldhistorie',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quelle', 'beschluss'), ('beschluss__isnull', False), ('import_referenz__isnull', True), ('quelle_wp__isnull', True)), models.Q(('quelle', 'import'), ('beschluss__isnull', True), ('import_referenz__isnull', False), ('quelle_wp__isnull', True)), models.Q(('quelle', 'wirtschaftsplan'), ('beschluss__isnull', True), ('import_referenz__isnull', True), ('quelle_wp__isnull', False)), _connector='OR'), name='hausgeld_historie_quelle_consistency'),
        ),
    ]
