# Generated by Django 5.1 on 2026-05-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personen', '0014_merge_20260525_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hausgeldhistorie',
            name='kontoart',
        ),
        migrations.AlterField(
            model_name='hausgeldhistorie',
            name='bemerkung',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='hausgeldhistorie',
            name='quelle',
            field=models.CharField(choices=[('beschluss', 'Beschluss'), ('import', 'Import (Massenimport / Erstanlage)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='briefanrede',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='briefanrede2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sepamandat',
            name='sequence_type',
            field=models.CharField(blank=True, choices=[('RCUR', 'Wiederkehrend (RCUR)'), ('FRST', 'Erstlastschrift (FRST)')], default='RCUR', help_text='FRST = Erstlastschrift, RCUR = Folgelastschrift', max_length=4, verbose_name='Sequenz-Typ'),
        ),
    ]
