# Generated by Django 5.1 on 2026-05-25 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung_wp', '0001_wp_initial'),
        ('buchhaltung', '0038_sollstellung_wp_felder'),
        ('konten', '0007_remove_konto_objekt'),
        ('personen', '0015_remove_hausgeldhistorie_kontoart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Constraint exists only in migration state, not in DB — update state only
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='hausgeldhistorie',
                    name='hausgeld_historie_quelle_consistency',
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='hausgeldhistorie',
            name='quelle_wp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hausgeld_historien', to='abrechnung_wp.wirtschaftsplan'),
        ),
        migrations.AddConstraint(
            model_name='hausgeldhistorie',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quelle', 'beschluss'), models.Q(('beschluss__isnull', False), ('quelle_wp__isnull', False), _connector='OR'), ('import_referenz__isnull', True)), models.Q(('quelle', 'import'), ('beschluss__isnull', True), ('quelle_wp__isnull', True), ('import_referenz__isnull', False)), _connector='OR'), name='hausgeld_historie_quelle_consistency'),
        ),
    ]
