# Generated by Django 5.1 on 2026-06-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personen', '0016_hausgeldhistorie_quelle_wp'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='titel',
            field=models.CharField(blank=True, default='', help_text='Akademischer Titel, z.B. Dr., Prof. Dr.', max_length=50, verbose_name='Titel'),
        ),
    ]
