# Generated by Django 5.1 on 2026-06-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personen', '0017_person_titel'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='titel2',
            field=models.CharField(blank=True, default='', help_text='Akademischer Titel der zweiten Person (bei Eheleuten)', max_length=50, verbose_name='Titel 2. Person'),
        ),
    ]
