# Generated by Django 5.1 on 2026-06-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personen', '0018_person_titel2'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='emails',
            field=models.JSONField(default=list, verbose_name='E-Mail-Adressen'),
        ),
        migrations.AddField(
            model_name='person',
            name='telefonnummern',
            field=models.JSONField(default=list, verbose_name='Telefonnummern'),
        ),
    ]
