# Generated by Django 5.1 on 2026-08-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personen', '0019_person_emails_telefonnummern'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hausnummer',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Hausnummer'),
        ),
        migrations.AddField(
            model_name='person',
            name='ort',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ort'),
        ),
        migrations.AddField(
            model_name='person',
            name='plz',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='PLZ'),
        ),
        migrations.AddField(
            model_name='person',
            name='strasse',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='person',
            name='adresse',
            field=models.TextField(blank=True, help_text='Automatisch aus Straße/Hausnummer/PLZ/Ort zusammengesetzt. Nicht direkt pflegen — die Einzelfelder sind führend.'),
        ),
    ]
