# Generated by Django 5.1 on 2026-09-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personen', '0021_seed_adress_einzelfelder'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='zustellweg',
            field=models.CharField(choices=[('post', 'Post'), ('email', 'E-Mail')], default='post', help_text='Bevorzugter Zustellweg für Schreiben; E-Mail nur mit Zustimmung.', max_length=10, verbose_name='Zustellweg'),
        ),
        migrations.AddField(
            model_name='person',
            name='zustellweg_zustimmung_am',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zustimmung E-Mail-Zustellung am'),
        ),
    ]
