# Generated by Django 5.1 on 2026-10-04 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personen', '0022_person_zustellweg_person_zustellweg_zustimmung_am'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='zustellungsbevollmaechtigter',
            field=models.ForeignKey(blank=True, help_text='Wenn gesetzt, gehen alle Schreiben, Mails und PDFs nur noch an diese Person (Typ Zustellungsbevollmächtigter).', limit_choices_to={'person_typ': '500'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vertretene_personen', to='personen.person', verbose_name='Zustellungsbevollmächtigter'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_typ',
            field=models.CharField(choices=[('100', 'Eigentümer'), ('200', 'Mieter'), ('300', 'Kreditor'), ('400', 'Sonstiges'), ('500', 'Zustellungsbevollmächtigter')], max_length=100),
        ),
    ]
